/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bestbuy.orders.fraud.model.client.orderdetails;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * FulfillmentPartner
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-19T01:15:20.679-08:00")
public class FulfillmentPartner {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("ffpPORefId")
  private String ffpPORefId = null;

  public FulfillmentPartner id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of fulfillment partner
   * @return id
  **/
  @ApiModelProperty(value = "ID of fulfillment partner")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FulfillmentPartner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of fulfillment partner
   * @return name
  **/
  @ApiModelProperty(value = "Name of fulfillment partner")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FulfillmentPartner type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FulfillmentPartner ffpPORefId(String ffpPORefId) {
    this.ffpPORefId = ffpPORefId;
    return this;
  }

   /**
   * Purchase order ID of fulfillment partner
   * @return ffpPORefId
  **/
  @ApiModelProperty(value = "Purchase order ID of fulfillment partner")
  public String getFfpPORefId() {
    return ffpPORefId;
  }

  public void setFfpPORefId(String ffpPORefId) {
    this.ffpPORefId = ffpPORefId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FulfillmentPartner fulfillmentPartner = (FulfillmentPartner) o;
    return Objects.equals(this.id, fulfillmentPartner.id) &&
        Objects.equals(this.name, fulfillmentPartner.name) &&
        Objects.equals(this.type, fulfillmentPartner.type) &&
        Objects.equals(this.ffpPORefId, fulfillmentPartner.ffpPORefId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, ffpPORefId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FulfillmentPartner {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    ffpPORefId: ").append(toIndentedString(ffpPORefId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

