/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bestbuy.orders.fraud.model.client.orderdetails;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * FulfillmentPartnerProduct
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-19T01:15:20.679-08:00")
public class FulfillmentPartnerProduct {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("rmsSKU")
  private String rmsSKU = null;

  @JsonProperty("vpn")
  private String vpn = null;

  public FulfillmentPartnerProduct name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FulfillmentPartnerProduct rmsSKU(String rmsSKU) {
    this.rmsSKU = rmsSKU;
    return this;
  }

   /**
   * Get rmsSKU
   * @return rmsSKU
  **/
  @ApiModelProperty(value = "")
  public String getRmsSKU() {
    return rmsSKU;
  }

  public void setRmsSKU(String rmsSKU) {
    this.rmsSKU = rmsSKU;
  }

  public FulfillmentPartnerProduct vpn(String vpn) {
    this.vpn = vpn;
    return this;
  }

   /**
   * Get vpn
   * @return vpn
  **/
  @ApiModelProperty(value = "")
  public String getVpn() {
    return vpn;
  }

  public void setVpn(String vpn) {
    this.vpn = vpn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FulfillmentPartnerProduct fulfillmentPartnerProduct = (FulfillmentPartnerProduct) o;
    return Objects.equals(this.name, fulfillmentPartnerProduct.name) &&
        Objects.equals(this.rmsSKU, fulfillmentPartnerProduct.rmsSKU) &&
        Objects.equals(this.vpn, fulfillmentPartnerProduct.vpn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, rmsSKU, vpn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FulfillmentPartnerProduct {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rmsSKU: ").append(toIndentedString(rmsSKU)).append("\n");
    sb.append("    vpn: ").append(toIndentedString(vpn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

