/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bestbuy.orders.fraud.model.client.orderdetails;

import java.util.Objects;
import ca.bestbuy.orders.fraud.model.client.orderdetails.Status;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PayPalInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-02T11:45:53.709-07:00")
public class PayPalInfo {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("avsStatus")
  private Status avsStatus = null;

  @JsonProperty("invoicedAmount")
  private String invoicedAmount = null;

  @JsonProperty("payPalInternalRefId")
  private String payPalInternalRefId = null;

  @JsonProperty("priority")
  private String priority = null;

  public PayPalInfo active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public PayPalInfo avsStatus(Status avsStatus) {
    this.avsStatus = avsStatus;
    return this;
  }

   /**
   * Get avsStatus
   * @return avsStatus
  **/
  @ApiModelProperty(value = "")
  public Status getAvsStatus() {
    return avsStatus;
  }

  public void setAvsStatus(Status avsStatus) {
    this.avsStatus = avsStatus;
  }

  public PayPalInfo invoicedAmount(String invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
    return this;
  }

   /**
   * Get invoicedAmount
   * @return invoicedAmount
  **/
  @ApiModelProperty(value = "")
  public String getInvoicedAmount() {
    return invoicedAmount;
  }

  public void setInvoicedAmount(String invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
  }

  public PayPalInfo payPalInternalRefId(String payPalInternalRefId) {
    this.payPalInternalRefId = payPalInternalRefId;
    return this;
  }

   /**
   * Get payPalInternalRefId
   * @return payPalInternalRefId
  **/
  @ApiModelProperty(value = "")
  public String getPayPalInternalRefId() {
    return payPalInternalRefId;
  }

  public void setPayPalInternalRefId(String payPalInternalRefId) {
    this.payPalInternalRefId = payPalInternalRefId;
  }

  public PayPalInfo priority(String priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public String getPriority() {
    return priority;
  }

  public void setPriority(String priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayPalInfo payPalInfo = (PayPalInfo) o;
    return Objects.equals(this.active, payPalInfo.active) &&
        Objects.equals(this.avsStatus, payPalInfo.avsStatus) &&
        Objects.equals(this.invoicedAmount, payPalInfo.invoicedAmount) &&
        Objects.equals(this.payPalInternalRefId, payPalInfo.payPalInternalRefId) &&
        Objects.equals(this.priority, payPalInfo.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, avsStatus, invoicedAmount, payPalInternalRefId, priority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayPalInfo {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    avsStatus: ").append(toIndentedString(avsStatus)).append("\n");
    sb.append("    invoicedAmount: ").append(toIndentedString(invoicedAmount)).append("\n");
    sb.append("    payPalInternalRefId: ").append(toIndentedString(payPalInternalRefId)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

