/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bestbuy.orders.fraud.model.client.orderdetails;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.joda.time.DateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * PurchaseOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-19T01:15:20.679-08:00")
public class PurchaseOrder {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("creationDate")
  private DateTime creationDate = null;

  @JsonProperty("fulfillmentPartner")
  private FulfillmentPartner fulfillmentPartner = null;

  @JsonProperty("poSendStatus")
  private Status poSendStatus = null;

  @JsonProperty("purchaseOrderLines")
  private List<PurchaseOrderLine> purchaseOrderLines = null;

  @JsonProperty("shippingOrderRefId")
  private String shippingOrderRefId = null;

  public PurchaseOrder id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PurchaseOrder creationDate(DateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(DateTime creationDate) {
    this.creationDate = creationDate;
  }

  public PurchaseOrder fulfillmentPartner(FulfillmentPartner fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
    return this;
  }

   /**
   * Get fulfillmentPartner
   * @return fulfillmentPartner
  **/
  @ApiModelProperty(value = "")
  public FulfillmentPartner getFulfillmentPartner() {
    return fulfillmentPartner;
  }

  public void setFulfillmentPartner(FulfillmentPartner fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
  }

  public PurchaseOrder poSendStatus(Status poSendStatus) {
    this.poSendStatus = poSendStatus;
    return this;
  }

   /**
   * Get poSendStatus
   * @return poSendStatus
  **/
  @ApiModelProperty(value = "")
  public Status getPoSendStatus() {
    return poSendStatus;
  }

  public void setPoSendStatus(Status poSendStatus) {
    this.poSendStatus = poSendStatus;
  }

  public PurchaseOrder purchaseOrderLines(List<PurchaseOrderLine> purchaseOrderLines) {
    this.purchaseOrderLines = purchaseOrderLines;
    return this;
  }

  public PurchaseOrder addPurchaseOrderLinesItem(PurchaseOrderLine purchaseOrderLinesItem) {
    if (this.purchaseOrderLines == null) {
      this.purchaseOrderLines = new ArrayList<PurchaseOrderLine>();
    }
    this.purchaseOrderLines.add(purchaseOrderLinesItem);
    return this;
  }

   /**
   * Get purchaseOrderLines
   * @return purchaseOrderLines
  **/
  @ApiModelProperty(value = "")
  public List<PurchaseOrderLine> getPurchaseOrderLines() {
    return purchaseOrderLines;
  }

  public void setPurchaseOrderLines(List<PurchaseOrderLine> purchaseOrderLines) {
    this.purchaseOrderLines = purchaseOrderLines;
  }

  public PurchaseOrder shippingOrderRefId(String shippingOrderRefId) {
    this.shippingOrderRefId = shippingOrderRefId;
    return this;
  }

   /**
   * Get shippingOrderRefId
   * @return shippingOrderRefId
  **/
  @ApiModelProperty(value = "")
  public String getShippingOrderRefId() {
    return shippingOrderRefId;
  }

  public void setShippingOrderRefId(String shippingOrderRefId) {
    this.shippingOrderRefId = shippingOrderRefId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrder purchaseOrder = (PurchaseOrder) o;
    return Objects.equals(this.id, purchaseOrder.id) &&
        Objects.equals(this.creationDate, purchaseOrder.creationDate) &&
        Objects.equals(this.fulfillmentPartner, purchaseOrder.fulfillmentPartner) &&
        Objects.equals(this.poSendStatus, purchaseOrder.poSendStatus) &&
        Objects.equals(this.purchaseOrderLines, purchaseOrder.purchaseOrderLines) &&
        Objects.equals(this.shippingOrderRefId, purchaseOrder.shippingOrderRefId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationDate, fulfillmentPartner, poSendStatus, purchaseOrderLines, shippingOrderRefId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrder {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    fulfillmentPartner: ").append(toIndentedString(fulfillmentPartner)).append("\n");
    sb.append("    poSendStatus: ").append(toIndentedString(poSendStatus)).append("\n");
    sb.append("    purchaseOrderLines: ").append(toIndentedString(purchaseOrderLines)).append("\n");
    sb.append("    shippingOrderRefId: ").append(toIndentedString(shippingOrderRefId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

