DROP SCHEMA ORDER_FRAUD IF EXISTS;
CREATE SCHEMA ORDER_FRAUD;

DROP TABLE ORDER_FRAUD.ID_GENERATOR IF EXISTS;
CREATE TABLE ORDER_FRAUD.ID_GENERATOR (
	GENERATED_NAME VARCHAR(80) NOT NULL,
	GENERATED_VALUE NUMBER NOT NULL
);
ALTER TABLE ORDER_FRAUD.ID_GENERATOR ADD CONSTRAINT ID_GENERATOR_PK PRIMARY KEY ( GENERATED_NAME );

DROP TABLE ORDER_FRAUD.FRAUD_RQST IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST (
    FRAUD_RQST_ID    NUMBER NOT NULL,
--  fs order number
    ORDER_NUMBER       NUMBER NOT NULL,
    EVENT_DATE         DATE NOT NULL,
--  every time oms moves the fso to fraud check required,we will create a new version
    REQUEST_VERSION    INTEGER NOT NULL,
    REQUEST_TYPE_CODE   VARCHAR2(80 CHAR) NOT NULL,
    FRAUD_STATUS_CODE   VARCHAR2(80 CHAR) NOT NULL,
	VERSION    		  INTEGER NOT NULL,
    CREATE_DATE        DATE NOT NULL,
    CREATE_USER        VARCHAR2(80 CHAR) NOT NULL,
    UPDATE_DATE        DATE NOT NULL,
    UPDATE_USER        VARCHAR2(80 CHAR) NOT NULL
);

ALTER TABLE ORDER_FRAUD.FRAUD_RQST ADD CONSTRAINT FRAUD_RQST_PK PRIMARY KEY ( FRAUD_RQST_ID );
ALTER TABLE ORDER_FRAUD.FRAUD_RQST ADD CONSTRAINT FRAUD_RQST_UN UNIQUE ( ORDER_NUMBER, REQUEST_VERSION );

DROP TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY (
    FRAUD_RQST_STATUS_HSTRY_ID   NUMBER NOT NULL,
    FRAUD_RQST_ID          NUMBER NOT NULL,
    FRAUD_STATUS_CODE         VARCHAR2(80 CHAR) NOT NULL,
	VERSION    		  		INTEGER NOT NULL,
    CREATE_DATE             	DATE NOT NULL,
    CREATE_USER              VARCHAR2(80 CHAR) NOT NULL,
    UPDATE_DATE              DATE NOT NULL,
    UPDATE_USER              VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY ADD CONSTRAINT FRAUD_RQST_STATUS_HSTRY_PK PRIMARY KEY ( FRAUD_RQST_STATUS_HSTRY_ID );


DROP TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS (
	FRAUD_RQST_STATUS_HSTRY_DTL_ID   NUMBER NOT NULL,
    FRAUD_RQST_STATUS_HSTRY_ID   NUMBER NOT NULL,
	FRAUD_RESPONSE_STATUS_CODE         VARCHAR2(80 CHAR) NOT NULL,
	TOTAL_FRAUD_SCORE	VARCHAR2(80 CHAR) NULL,
	RECOMMENDATION_CODE	VARCHAR2(400 CHAR) NULL,
	ACCERTIFY_USER	VARCHAR2(80 CHAR) NULL,
	ACCERTIFY_USER_ACTION_TIME	DATE NULL,
    TAS_REQUEST              CLOB NULL,
    TAS_RESPONSE             CLOB NULL,
    VERSION    		  		INTEGER NOT NULL,
	CREATE_DATE              DATE NOT NULL,
    CREATE_USER              VARCHAR2(80) NOT NULL,
    UPDATE_DATE              DATE NOT NULL,
    UPDATE_USER              VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS ADD CONSTRAINT FRD_RQST_STATUS_HSTRY_DTLS_PK PRIMARY KEY ( FRAUD_RQST_STATUS_HSTRY_DTL_ID );


DROP TABLE ORDER_FRAUD.FRAUD_STATUSES IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_STATUSES (
    FRAUD_STATUS_CODE          VARCHAR2(80) NOT NULL,
    FRAUD_STATUS_DESCRIPTION   VARCHAR2(2000 CHAR),
    VERSION    		  		 INTEGER NOT NULL,
	CREATE_DATE               DATE NOT NULL,
    CREATE_USER               VARCHAR2(80) NOT NULL,
    UPDATE_DATE               DATE NOT NULL,
    UPDATE_USER               VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_STATUSES ADD CONSTRAINT FRAUD_STATUSES_PK PRIMARY KEY ( FRAUD_STATUS_CODE );


DROP TABLE ORDER_FRAUD.FRAUD_RQST_TYPES IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_TYPES (
    REQUEST_TYPE_CODE          VARCHAR2(80 CHAR) NOT NULL,
    REQUEST_TYPE_DESCRIPTION   VARCHAR2(2000),
    VERSION    		  		 INTEGER NOT NULL,
	CREATE_DATE               DATE NOT NULL,
    CREATE_USER               VARCHAR2(80) NOT NULL,
    UPDATE_DATE               DATE NOT NULL,
    UPDATE_USER               VARCHAR2(80 CHAR) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_TYPES ADD CONSTRAINT FRAUD_RQST_TYPES_PK PRIMARY KEY ( REQUEST_TYPE_CODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST
    ADD CONSTRAINT FRDRQST_FRDSTATUSES_FK FOREIGN KEY ( FRAUD_STATUS_CODE )
        REFERENCES ORDER_FRAUD.FRAUD_STATUSES ( FRAUD_STATUS_CODE );
		
ALTER TABLE ORDER_FRAUD.FRAUD_RQST
    ADD CONSTRAINT FRDRQST_RQST_TYPS_FK FOREIGN KEY ( REQUEST_TYPE_CODE )
        REFERENCES ORDER_FRAUD.FRAUD_RQST_TYPES ( REQUEST_TYPE_CODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY 
    ADD CONSTRAINT FRDRQSTHSTRY_FRDRQST_FK FOREIGN KEY ( FRAUD_RQST_ID ) 
        REFERENCES ORDER_FRAUD.FRAUD_RQST ( FRAUD_RQST_ID );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY
    ADD CONSTRAINT FRDRQSTHSTRY_FRDSTATUSES_FK FOREIGN KEY ( FRAUD_STATUS_CODE )
        REFERENCES ORDER_FRAUD.FRAUD_STATUSES ( FRAUD_STATUS_CODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS
    ADD CONSTRAINT FRDRQSTHSTRYDTL_FRDRQSTHTRY_FK FOREIGN KEY ( FRAUD_RQST_STATUS_HSTRY_ID )
        REFERENCES ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY ( FRAUD_RQST_STATUS_HSTRY_ID );