server:
  port: 8090
  contextPath: /orderfraud

spring:
  profiles: dev
logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: WARN

---

spring:
  profiles: test
logging:
  level:
    ca.bestbuy: INFO
    ROOT: WARN

---

spring:
  profiles: prod
logging:
  level:
    ca.bestbuy: INFO
    ROOT: WARN

---

