spring:
  datasource:
    url: jdbc:h2:mem:order-fraud
    platform: h2
    username: test
    password:
    driverClassName: org.h2.Driver
    schema: classpath:relationaldb/h2-ddl.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console