server:
  port: 8090
  contextPath: /orderfraud

spring:
  profiles:
    # set the profile to be 'dev' by default
    # this can be overridden by setting the system property
    active: dev

---
#### DEVELOPMENT ####

spring:
  profiles: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: orders
  cloud:
    stream:
      bindings:
        fraudInbound:
          destination: fraudInbound
          group: fraudInboundConsumersGroup
          consumer:
            concurrency: 20
            maxAttempts: 1
        fraudOutbound:
          destination: fraudOutbound
      rabbit:
        bindings:
          fraudInbound:
            consumer:
              autoBindDlq: true
              dlqTtl: 10000
              republishToDlq: true
              #Using default exchange so dlqDeadLetterExchange is assigned to empty string
              dlqDeadLetterExchange:
      default:
        contentType: application/json

###
#   Database Settings
###
  datasource:
    url: jdbc:oracle:thin:@//ecommtcls01-scan.ca.bestbuy.com:50000/dbs_cwbci05
    platform: oracle
    username: order_fraud_user
    password: order_fraud_user99
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

messaging:
  errorRetryCount: 3


logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: INFO

# Configuration for any services that Order Fraud Service will need to call
client:
  order-details:
    connection:
      # REQUIRED
      url: dummyUrl
      # REQUIRED - REST endpoint for getOrderDetails
      getOrderDetailsEndpoint: dummy
      timeout:
        # Timeout for establishing a connection (in milliseconds)
        connection: ~
        # Timeout for waiting for response after request is sent (in milliseconds)
        request: ~
      ssl:
        # REQUIRED - Indicates whether SSL is enabled (true/false)
        enabled: false
        # Indicates whether hostname verification should be enabled (true/false, default: true)
        verify-hostname: ~
        # REQUIRED (only if ssl.enabled = true) - Path to keystore (JKS or PKCS#12)
        # - If specifying a system file, add prefix with 'file:'
        # - If specifying a classpath file, add prefix with 'classpath:'
        keystore: ~
        # REQUIRED (only if ssl.enabled = true)
        keystore-password: ~
        # OPTIONAL - Alias of key-entry
        key-alias: ~
        # OPTIONAL - Password of key
        # Note: If not set, will use keystore-password as key-password
        key-password: ~
        # REQUIRED (only if ssl.enabled = true) - Path to truststore (JKS or PKCS#12)
        # - If specifying a system file, add prefix with 'file:'
        # - If specifying a classpath file, add prefix with 'classpath:'
        truststore: ~
        # REQUIRED (only if ssl.enabled = true)
        truststore-password: ~

  resource-api:
    connection:
      url: https://di-bbyca-resourceservice-corp.ca.bestbuy.com
      endpoint: /aggregator
      timeout:
        # Timeout for establishing a connection (in milliseconds)
        connection: ~
        # Timeout for waiting for response after request is sent (in milliseconds)
        request: ~
      ssl:
        enabled: false
        keystore: ~
        keystore-password: mccp123
        truststore: ~
        truststore-password: changeit

  tas:
    connection:
      # REQUIRED
      url: dummyUrl
      # REQUIRED - SOAP action callback for fraudCheck operation
      fraudcheck-soap-action-callback: fraudMockService
      timeout:
        # Timeout for establishing a connection (in milliseconds)
        connection: ~
        # Timeout for waiting for response after request is sent (in milliseconds)
        request: ~
      ssl:
        # REQUIRED - Indicates whether SSL is enabled (true/false)
        enabled: false
        # Indicates whether hostname verification should be enabled (true/false, default: true)
        verify-hostname: ~
        # REQUIRED (only if ssl.enabled = true) - Path to keystore (JKS or PKCS#12)
        # - If specifying a system file, add prefix with 'file:'
        # - If specifying a classpath file, add prefix with 'classpath:'
        keystore: ~
        # REQUIRED (only if ssl.enabled = true)
        keystore-password: ~
        # OPTIONAL - Alias of key-entry
        key-alias: ~
        # OPTIONAL - Password of key
        # Note: If not set, will use keystore-password as key-password
        key-password: ~
        # REQUIRED (only if ssl.enabled = true) - Path to truststore (JKS or PKCS#12)
        # - If specifying a system file, add prefix with 'file:'
        # - If specifying a classpath file, add prefix with 'classpath:'
        truststore: ~
        # REQUIRED (only if ssl.enabled = true)
        truststore-password: ~
---
#### UNIT TEST ####

spring:
  profiles: unittest

###
#   Unittest Database Settings
###
  datasource:
    url: jdbc:h2:mem:order-fraud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: test
    password:
    driverClassName: org.h2.Driver
    schema: classpath:relationaldb/h2-ddl.sql
    data: classpath:relationaldb/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
###
#   Unittest H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console

      settings:
        trace: false
        web-allow-others: true
