server:
  port: 8090
  contextPath: /orderfraud

---
### DEVELOPMENT ###

spring:
  profiles: dev

  # For config options, see https://codecentric.github.io/spring-boot-admin/1.5.7/
  boot:
    admin:
      client:
        enabled: true
        health-url: http://localhost:${server.port}/${server.contextPath}/health
        management-url: http://localhost:${server.port}/${server.contextPath}
        service-url: http://localhost:${server.port}/${server.contextPath}/swagger-ui.html
      url: http://localhost:8100
      username: admin
      password: admin
      auto-deregistration: true # Automatically de-register this application when it shuts down
  rabbitmq:
    host: localhost
    port: 5672
    username: orders # Login user to authenticate to the RabbitMQ broker
    password: orders # Login password to authenticate against the RabbitMQ broker
    virtual-host: orders # Virtual host to use when connecting to the RabbitMQ broker
  cloud:
    stream:
      bindings:
        fraudInbound:
          destination: fraudInbound # Inbound exchange
          group: fraudInboundConsumersGroup
          consumer:
            concurrency: 20 # The concurrency of the inbound consumer
            maxAttempts: 1 # The number of attempts of re-processing an inbound message
        fraudOutbound:
          destination: fraudOutbound # Outbound exchange
          producer:
            requiredGroups: fraudOutboundConsumersGroup
      rabbit:
        bindings:
          fraudInbound:
            consumer:
              autoBindDlq: true
              dlqTtl: 10000
              republishToDlq: true
              dlqDeadLetterExchange: # Using default exchange so dlqDeadLetterExchange is assigned to empty string
      default:
        contentType: application/json

# Database settings
# Note: If you want to use H2, you can use the h2 profile along with dev
  datasource:
    url: jdbc:oracle:thin:@//ecommtcls01-scan.ca.bestbuy.com:50000/dbs_cwbci05 # JDBC URL of the database
    platform: oracle # Platform to use in the DDL or DML scripts
    username: order_fraud_user # Login username of the database
    password: order_fraud_user99 # Login password of the database
    driver-class-name: oracle.jdbc.OracleDriver # Fully qualified name of the JDBC driver.
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

messaging:
  errorRetryCount: 3
  outbound:
    retry-attempts: 3 # Number of attempts to retry if unable to place message on outbound queue | Default: 0
    timeout: 10000 # (ms)

# Logging configurations
logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: INFO

# Configuration for any services that Order Fraud Service will need to call
client:
  order-details:
    connection:
      url: dummyUrl # Base URL
      getOrderDetailsEndpoint: dummy
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~
  resource-api:
    connection:
      url: https://di-bbyca-resourceservice-corp.ca.bestbuy.com # Base URL
      endpoint: /aggregator
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: mccp123
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: changeit
  tas:
    connection:
      url: dummyUrl # Base URL
      fraudcheck-soap-action-callback: fraudMockService
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~
  payment-service:
    connection:
      url: dummyUrl # Base URL
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~
