server:
  port: 8090
  contextPath: /orderfraud
    
spring:
  rabbitmq:
    host: dtl24vmqcix51.ca.bestbuy.com
    port: 5672
    username: guest
    password: guest
    virtual-host: orders
 
  cloud:
    stream:
      bindings:
        fraudInbound:
          destination: fraudInbound
          group: fraudInboundConsumersGroup
          consumer:
            concurrency:  20
            maxAttempts: 1
        fraudOutbound:
          destination: fraudOutbound
      rabbit:
        bindings:
          fraudInbound:
            consumer:
              autoBindDlq:  true
              dlqTtl: 10000
              republishToDlq: true
              #Using default exchange so dlqDeadLetterExchange is assigned to empty string 
              dlqDeadLetterExchange: 
      default: 
        contentType:  application/json 

messaging:
  errorRetryCount: 3

client:
  order-details:
    connection:
      url: http://localhost:8080/orderdetails
      getOrderDetailsEndpoint: /v1/fsorders
      keystore-path: ~
      keystore-password: ~
      keystore-type: ~
      key-alias: ~
      key-password: ~
      truststore-path: ~
      truststore-password: ~
      truststore-type: JKS
      tls-enabled: false