spring:
  profiles: dev
logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: DEBUG

---

spring:
  profiles: test
logging:
  level:
    ca.bestbuy: INFO

---

spring:
  profiles: prod
logging:
  level:
    ROOT: WARN
    ca.bestbuy: INFO

---

