#
# Configurations for application
# For an explanation on the different configurations, see the following link on Confluence:
# - https://confluence.ca.bestbuy.com/pages/viewpage.action?pageId=30666366
#

server:
  port: 8090
  contextPath: /orderfraud

---
### DEVELOPMENT ###

spring:
  profiles: dev

  # For config options, see https://codecentric.github.io/spring-boot-admin/1.5.7/
  boot:
    admin:
      client:
        enabled: false
      url: http://localhost:8100
      username: admin
      password: admin
      # Automatically de-register this application when it shuts down
      auto-deregistration: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: orders
  cloud:
    stream:
      bindings:
        fraudInbound:
          destination: fraudInbound
          group: fraudInboundConsumersGroup
          consumer:
            concurrency: 20
            maxAttempts: 1
        fraudOutbound:
          destination: fraudOutbound
          producer:
            requiredGroups: fraudOutboundConsumersGroup
      rabbit:
        bindings:
          fraudInbound:
            consumer:
              autoBindDlq: true
              dlqTtl: 10000
              republishToDlq: true
              # Using default exchange so dlqDeadLetterExchange is assigned to empty string
              dlqDeadLetterExchange:
      default:
        contentType: application/json

# Database settings
# Note: If you want to use H2, you can use the h2 profile along with dev
  datasource:
    url: jdbc:oracle:thin:@//ecommtcls01-scan.ca.bestbuy.com:50000/dbs_cwbci05
    platform: oracle
    username: order_fraud_user
    password: order_fraud_user99
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

messaging:
  errorRetryCount: 3
  outbound:
    retry-attempts: 3 # Default: 0
    timeout: 10000 # (ms)

logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: INFO

# Configuration for any services that Order Fraud Service will need to call
client:
  order-details:
    connection:
      url: dummyUrl
      getOrderDetailsEndpoint: dummy
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~
  resource-api:
    connection:
      url: https://di-bbyca-resourceservice-corp.ca.bestbuy.com
      endpoint: /aggregator
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: mccp123
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: changeit
  tas:
    connection:
      url: dummyUrl
      fraudcheck-soap-action-callback: fraudMockService
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~
  payment-service:
    connection:
      url: dummyUrl
      timeout:
        connection: ~ # (ms)
        request: ~ # (ms)
      ssl:
        enabled: false
        verify-hostname: ~ # Default: true
        keystore: ~ # Prefix with file: or classpath:
        keystore-password: ~
        key-alias: ~ # (Optional)
        key-password: ~ # (Optional)
        truststore: ~ # Prefix with file: or classpath:
        truststore-password: ~