server:
  port: 8090
  contextPath: /orderfraud

info:
  name: @project.name@
  version: @project.version@

---

spring:
  profiles: dev
logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: WARN

---

spring:
  profiles: test
logging:
  level:
    ca.bestbuy: INFO
    ROOT: WARN

---

spring:
  profiles: prod
logging:
  level:
    ca.bestbuy: INFO
    ROOT: WARN

---

###
#   Database Settings
###
spring:  
  profiles: unittest
  datasource:
    url: jdbc:h2:mem:order-fraud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: test
    password: 
    driverClassName: org.h2.Driver
    schema: classpath:relationaldb/h2-ddl.sql
    data: classpath:relationaldb/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      
      settings:
        trace: false
        web-allow-others: true
---
###
#   Database Settings
###
spring:  
  datasource:
    url: jdbc:oracle:thin:@//ecommtcls01-scan.ca.bestbuy.com:50000/dbs_cwbci05
    platform: oracle
    username: order_fraud_user
    password: order_fraud_user99
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true