server:
  port: 8090
  contextPath: /orderfraud

spring:
  profiles:
    # set the profile to be 'dev' by default
    # this can be overridden by setting the system property
    active: dev

---

spring:
  profiles: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: orders

  cloud:
    stream:
      bindings:
        fraudInbound:
          destination: fraudInbound
          group: fraudInboundConsumersGroup
          consumer:
            concurrency:  20
            maxAttempts: 1
        fraudOutbound:
          destination: fraudOutbound
      rabbit:
        bindings:
          fraudInbound:
            consumer:
              autoBindDlq:  true
              dlqTtl: 10000
              republishToDlq: true
              #Using default exchange so dlqDeadLetterExchange is assigned to empty string
              dlqDeadLetterExchange:
      default:
        contentType:  application/json

###
#   Database Settings
###
  datasource:
    url: jdbc:oracle:thin:@//ecommtcls01-scan.ca.bestbuy.com:50000/dbs_cwbci05
    platform: oracle
    username: order_fraud_user
    password: order_fraud_user99
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

messaging:
  errorRetryCount: 3

client:
  order-details:
    connection:
      url: http://localhost:8080/orderdetails
      getOrderDetailsEndpoint: /v1/fsorders
      keystore-path: ~
      keystore-password: ~
      keystore-type: ~
      key-alias: ~
      key-password: ~
      truststore-path: ~
      truststore-password: ~
      truststore-type: JKS
      tls-enabled: false

  tas:
    connection:
      url: ~
      fraudCheckOperation: fraudMockService
      hostname: ~
      connectionTimeout: 10000
      readTimeout: 15000
      ssl:
        verify-hostname: false
        key-alias: ~
        keystore-path: ~
        keystore-password: ~
        keystore-type: JKS
        truststore-path: ~
        truststore-password: ~
        truststore-type: JKS
        tls-enabled: false

logging:
  level:
    ca.bestbuy: DEBUG
    # ROOT: WARN means that any logging context not matching a context described above will be filtered to level WARN
    ROOT: INFO

---

###
#   Unittest Database Settings
###
spring:
  profiles: unittest
  datasource:
    url: jdbc:h2:mem:order-fraud;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: test
    password:
    driverClassName: org.h2.Driver
    schema: classpath:relationaldb/h2-ddl.sql
    data: classpath:relationaldb/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   Unittest H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console

      settings:
        trace: false
        web-allow-others: true
