/*
 * Fraud  service REST API
 * REST API for retrive and update fraud request
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ca.bestbuy.orders.fraud.callback.model.swagger.api;

import java.util.Objects;
import ca.bestbuy.orders.fraud.callback.model.swagger.api.FraudResultDetail;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * FraudResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-23T21:43:53.586-07:00")
public class FraudResult {
  @JsonProperty("crossReference")
  private String crossReference = null;

  @JsonProperty("rulesExecuted")
  private String rulesExecuted = null;

  @JsonProperty("totalScore")
  private Integer totalScore = null;

  @JsonProperty("updateUser")
  private String updateUser = null;

  @JsonProperty("updateDateTime")
  private DateTime updateDateTime = null;

  @JsonProperty("fraudResultDetail")
  private FraudResultDetail fraudResultDetail = null;

  public FraudResult crossReference(String crossReference) {
    this.crossReference = crossReference;
    return this;
  }

   /**
   * Get crossReference
   * @return crossReference
  **/
  @ApiModelProperty(value = "")
  public String getCrossReference() {
    return crossReference;
  }

  public void setCrossReference(String crossReference) {
    this.crossReference = crossReference;
  }

  public FraudResult rulesExecuted(String rulesExecuted) {
    this.rulesExecuted = rulesExecuted;
    return this;
  }

   /**
   * Get rulesExecuted
   * @return rulesExecuted
  **/
  @ApiModelProperty(value = "")
  public String getRulesExecuted() {
    return rulesExecuted;
  }

  public void setRulesExecuted(String rulesExecuted) {
    this.rulesExecuted = rulesExecuted;
  }

  public FraudResult totalScore(Integer totalScore) {
    this.totalScore = totalScore;
    return this;
  }

   /**
   * Get totalScore
   * @return totalScore
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalScore() {
    return totalScore;
  }

  public void setTotalScore(Integer totalScore) {
    this.totalScore = totalScore;
  }

  public FraudResult updateUser(String updateUser) {
    this.updateUser = updateUser;
    return this;
  }

   /**
   * Get updateUser
   * @return updateUser
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUpdateUser() {
    return updateUser;
  }

  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  public FraudResult updateDateTime(DateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
    return this;
  }

   /**
   * Get updateDateTime
   * @return updateDateTime
  **/
  @ApiModelProperty(value = "")
  public DateTime getUpdateDateTime() {
    return updateDateTime;
  }

  public void setUpdateDateTime(DateTime updateDateTime) {
    this.updateDateTime = updateDateTime;
  }

  public FraudResult fraudResultDetail(FraudResultDetail fraudResultDetail) {
    this.fraudResultDetail = fraudResultDetail;
    return this;
  }

   /**
   * Get fraudResultDetail
   * @return fraudResultDetail
  **/
  @ApiModelProperty(required = true, value = "")
  public FraudResultDetail getFraudResultDetail() {
    return fraudResultDetail;
  }

  public void setFraudResultDetail(FraudResultDetail fraudResultDetail) {
    this.fraudResultDetail = fraudResultDetail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FraudResult fraudResult = (FraudResult) o;
    return Objects.equals(this.crossReference, fraudResult.crossReference) &&
        Objects.equals(this.rulesExecuted, fraudResult.rulesExecuted) &&
        Objects.equals(this.totalScore, fraudResult.totalScore) &&
        Objects.equals(this.updateUser, fraudResult.updateUser) &&
        Objects.equals(this.updateDateTime, fraudResult.updateDateTime) &&
        Objects.equals(this.fraudResultDetail, fraudResult.fraudResultDetail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crossReference, rulesExecuted, totalScore, updateUser, updateDateTime, fraudResultDetail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FraudResult {\n");
    
    sb.append("    crossReference: ").append(toIndentedString(crossReference)).append("\n");
    sb.append("    rulesExecuted: ").append(toIndentedString(rulesExecuted)).append("\n");
    sb.append("    totalScore: ").append(toIndentedString(totalScore)).append("\n");
    sb.append("    updateUser: ").append(toIndentedString(updateUser)).append("\n");
    sb.append("    updateDateTime: ").append(toIndentedString(updateDateTime)).append("\n");
    sb.append("    fraudResultDetail: ").append(toIndentedString(fraudResultDetail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

