/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ActualCarrier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class ActualCarrier {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("levelOfService")
  private LevelOfService levelOfService = null;

  @JsonProperty("shipmentType")
  private String shipmentType = null;

  @JsonProperty("trackingHttpMethod")
  private String trackingHttpMethod = null;

  @JsonProperty("trackingNumbers")
  private TrackingNumbers trackingNumbers = null;

  @JsonProperty("trackingParameter")
  private String trackingParameter = null;

  @JsonProperty("trackingURL")
  private String trackingURL = null;

  public ActualCarrier id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActualCarrier levelOfService(LevelOfService levelOfService) {
    this.levelOfService = levelOfService;
    return this;
  }

   /**
   * Get levelOfService
   * @return levelOfService
  **/
  @ApiModelProperty(value = "")
  public LevelOfService getLevelOfService() {
    return levelOfService;
  }

  public void setLevelOfService(LevelOfService levelOfService) {
    this.levelOfService = levelOfService;
  }

  public ActualCarrier shipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
    return this;
  }

   /**
   * Get shipmentType
   * @return shipmentType
  **/
  @ApiModelProperty(value = "")
  public String getShipmentType() {
    return shipmentType;
  }

  public void setShipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
  }

  public ActualCarrier trackingHttpMethod(String trackingHttpMethod) {
    this.trackingHttpMethod = trackingHttpMethod;
    return this;
  }

   /**
   * Get trackingHttpMethod
   * @return trackingHttpMethod
  **/
  @ApiModelProperty(value = "")
  public String getTrackingHttpMethod() {
    return trackingHttpMethod;
  }

  public void setTrackingHttpMethod(String trackingHttpMethod) {
    this.trackingHttpMethod = trackingHttpMethod;
  }

  public ActualCarrier trackingNumbers(TrackingNumbers trackingNumbers) {
    this.trackingNumbers = trackingNumbers;
    return this;
  }

   /**
   * Get trackingNumbers
   * @return trackingNumbers
  **/
  @ApiModelProperty(value = "")
  public TrackingNumbers getTrackingNumbers() {
    return trackingNumbers;
  }

  public void setTrackingNumbers(TrackingNumbers trackingNumbers) {
    this.trackingNumbers = trackingNumbers;
  }

  public ActualCarrier trackingParameter(String trackingParameter) {
    this.trackingParameter = trackingParameter;
    return this;
  }

   /**
   * Get trackingParameter
   * @return trackingParameter
  **/
  @ApiModelProperty(value = "")
  public String getTrackingParameter() {
    return trackingParameter;
  }

  public void setTrackingParameter(String trackingParameter) {
    this.trackingParameter = trackingParameter;
  }

  public ActualCarrier trackingURL(String trackingURL) {
    this.trackingURL = trackingURL;
    return this;
  }

   /**
   * Get trackingURL
   * @return trackingURL
  **/
  @ApiModelProperty(value = "")
  public String getTrackingURL() {
    return trackingURL;
  }

  public void setTrackingURL(String trackingURL) {
    this.trackingURL = trackingURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActualCarrier actualCarrier = (ActualCarrier) o;
    return Objects.equals(this.id, actualCarrier.id) &&
        Objects.equals(this.levelOfService, actualCarrier.levelOfService) &&
        Objects.equals(this.shipmentType, actualCarrier.shipmentType) &&
        Objects.equals(this.trackingHttpMethod, actualCarrier.trackingHttpMethod) &&
        Objects.equals(this.trackingNumbers, actualCarrier.trackingNumbers) &&
        Objects.equals(this.trackingParameter, actualCarrier.trackingParameter) &&
        Objects.equals(this.trackingURL, actualCarrier.trackingURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, levelOfService, shipmentType, trackingHttpMethod, trackingNumbers, trackingParameter, trackingURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActualCarrier {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    levelOfService: ").append(toIndentedString(levelOfService)).append("\n");
    sb.append("    shipmentType: ").append(toIndentedString(shipmentType)).append("\n");
    sb.append("    trackingHttpMethod: ").append(toIndentedString(trackingHttpMethod)).append("\n");
    sb.append("    trackingNumbers: ").append(toIndentedString(trackingNumbers)).append("\n");
    sb.append("    trackingParameter: ").append(toIndentedString(trackingParameter)).append("\n");
    sb.append("    trackingURL: ").append(toIndentedString(trackingURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

