/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Bundle
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class Bundle {
  @JsonProperty("bundleID")
  private String bundleID = null;

  @JsonProperty("seqNum")
  private String seqNum = null;

  public Bundle bundleID(String bundleID) {
    this.bundleID = bundleID;
    return this;
  }

   /**
   * Get bundleID
   * @return bundleID
  **/
  @ApiModelProperty(value = "")
  public String getBundleID() {
    return bundleID;
  }

  public void setBundleID(String bundleID) {
    this.bundleID = bundleID;
  }

  public Bundle seqNum(String seqNum) {
    this.seqNum = seqNum;
    return this;
  }

   /**
   * Get seqNum
   * @return seqNum
  **/
  @ApiModelProperty(value = "")
  public String getSeqNum() {
    return seqNum;
  }

  public void setSeqNum(String seqNum) {
    this.seqNum = seqNum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bundle bundle = (Bundle) o;
    return Objects.equals(this.bundleID, bundle.bundleID) &&
        Objects.equals(this.seqNum, bundle.seqNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleID, seqNum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bundle {\n");
    
    sb.append("    bundleID: ").append(toIndentedString(bundleID)).append("\n");
    sb.append("    seqNum: ").append(toIndentedString(seqNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

