/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetailsservice.CardholderName;
import com.bbyc.orders.model.client.orderdetailsservice.ExpiryDate;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CreditCard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class CreditCard {
  @JsonProperty("cardholderName")
  private CardholderName cardholderName = null;

  @JsonProperty("ccnumber")
  private Integer ccnumber = null;

  @JsonProperty("cctype")
  private String cctype = null;

  @JsonProperty("expiryDate")
  private ExpiryDate expiryDate = null;

  public CreditCard cardholderName(CardholderName cardholderName) {
    this.cardholderName = cardholderName;
    return this;
  }

   /**
   * Get cardholderName
   * @return cardholderName
  **/
  @ApiModelProperty(value = "")
  public CardholderName getCardholderName() {
    return cardholderName;
  }

  public void setCardholderName(CardholderName cardholderName) {
    this.cardholderName = cardholderName;
  }

  public CreditCard ccnumber(Integer ccnumber) {
    this.ccnumber = ccnumber;
    return this;
  }

   /**
   * Get ccnumber
   * @return ccnumber
  **/
  @ApiModelProperty(value = "")
  public Integer getCcnumber() {
    return ccnumber;
  }

  public void setCcnumber(Integer ccnumber) {
    this.ccnumber = ccnumber;
  }

  public CreditCard cctype(String cctype) {
    this.cctype = cctype;
    return this;
  }

   /**
   * Get cctype
   * @return cctype
  **/
  @ApiModelProperty(value = "")
  public String getCctype() {
    return cctype;
  }

  public void setCctype(String cctype) {
    this.cctype = cctype;
  }

  public CreditCard expiryDate(ExpiryDate expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @ApiModelProperty(value = "")
  public ExpiryDate getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(ExpiryDate expiryDate) {
    this.expiryDate = expiryDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditCard creditCard = (CreditCard) o;
    return Objects.equals(this.cardholderName, creditCard.cardholderName) &&
        Objects.equals(this.ccnumber, creditCard.ccnumber) &&
        Objects.equals(this.cctype, creditCard.cctype) &&
        Objects.equals(this.expiryDate, creditCard.expiryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardholderName, ccnumber, cctype, expiryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditCard {\n");
    
    sb.append("    cardholderName: ").append(toIndentedString(cardholderName)).append("\n");
    sb.append("    ccnumber: ").append(toIndentedString(ccnumber)).append("\n");
    sb.append("    cctype: ").append(toIndentedString(cctype)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

