/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * FSOrderLine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class FSOrderLine {
  @JsonProperty("bundle")
  private Bundle bundle = null;

  @JsonProperty("configureToOrderID")
  private String configureToOrderID = null;

  @JsonProperty("etaDate")
  private String etaDate = null;

  @JsonProperty("fsolStatus")
  private FsolStatus fsolStatus = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("itemCharge")
  private ItemCharge itemCharge = null;

  @JsonProperty("linenum")
  private String linenum = null;

  @JsonProperty("product")
  private Product product = null;

  @JsonProperty("pspcoveredFSOrderlineID")
  private String pspcoveredFSOrderlineID = null;

  @JsonProperty("qtyCancelled")
  private String qtyCancelled = null;

  @JsonProperty("qtyOnSpecialOrder")
  private String qtyOnSpecialOrder = null;

  @JsonProperty("qtyOrdered")
  private String qtyOrdered = null;

  @JsonProperty("releaseDate")
  private String releaseDate = null;

  @JsonProperty("uom")
  private String uom = null;

  public FSOrderLine bundle(Bundle bundle) {
    this.bundle = bundle;
    return this;
  }

   /**
   * Get bundle
   * @return bundle
  **/
  @ApiModelProperty(value = "")
  public Bundle getBundle() {
    return bundle;
  }

  public void setBundle(Bundle bundle) {
    this.bundle = bundle;
  }

  public FSOrderLine configureToOrderID(String configureToOrderID) {
    this.configureToOrderID = configureToOrderID;
    return this;
  }

   /**
   * Get configureToOrderID
   * @return configureToOrderID
  **/
  @ApiModelProperty(value = "")
  public String getConfigureToOrderID() {
    return configureToOrderID;
  }

  public void setConfigureToOrderID(String configureToOrderID) {
    this.configureToOrderID = configureToOrderID;
  }

  public FSOrderLine etaDate(String etaDate) {
    this.etaDate = etaDate;
    return this;
  }

   /**
   * Get etaDate
   * @return etaDate
  **/
  @ApiModelProperty(value = "")
  public String getEtaDate() {
    return etaDate;
  }

  public void setEtaDate(String etaDate) {
    this.etaDate = etaDate;
  }

  public FSOrderLine fsolStatus(FsolStatus fsolStatus) {
    this.fsolStatus = fsolStatus;
    return this;
  }

   /**
   * Get fsolStatus
   * @return fsolStatus
  **/
  @ApiModelProperty(value = "")
  public FsolStatus getFsolStatus() {
    return fsolStatus;
  }

  public void setFsolStatus(FsolStatus fsolStatus) {
    this.fsolStatus = fsolStatus;
  }

  public FSOrderLine id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FSOrderLine itemCharge(ItemCharge itemCharge) {
    this.itemCharge = itemCharge;
    return this;
  }

   /**
   * Get itemCharge
   * @return itemCharge
  **/
  @ApiModelProperty(value = "")
  public ItemCharge getItemCharge() {
    return itemCharge;
  }

  public void setItemCharge(ItemCharge itemCharge) {
    this.itemCharge = itemCharge;
  }

  public FSOrderLine linenum(String linenum) {
    this.linenum = linenum;
    return this;
  }

   /**
   * Get linenum
   * @return linenum
  **/
  @ApiModelProperty(value = "")
  public String getLinenum() {
    return linenum;
  }

  public void setLinenum(String linenum) {
    this.linenum = linenum;
  }

  public FSOrderLine product(Product product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(value = "")
  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public FSOrderLine pspcoveredFSOrderlineID(String pspcoveredFSOrderlineID) {
    this.pspcoveredFSOrderlineID = pspcoveredFSOrderlineID;
    return this;
  }

   /**
   * Get pspcoveredFSOrderlineID
   * @return pspcoveredFSOrderlineID
  **/
  @ApiModelProperty(value = "")
  public String getPspcoveredFSOrderlineID() {
    return pspcoveredFSOrderlineID;
  }

  public void setPspcoveredFSOrderlineID(String pspcoveredFSOrderlineID) {
    this.pspcoveredFSOrderlineID = pspcoveredFSOrderlineID;
  }

  public FSOrderLine qtyCancelled(String qtyCancelled) {
    this.qtyCancelled = qtyCancelled;
    return this;
  }

   /**
   * Get qtyCancelled
   * @return qtyCancelled
  **/
  @ApiModelProperty(value = "")
  public String getQtyCancelled() {
    return qtyCancelled;
  }

  public void setQtyCancelled(String qtyCancelled) {
    this.qtyCancelled = qtyCancelled;
  }

  public FSOrderLine qtyOnSpecialOrder(String qtyOnSpecialOrder) {
    this.qtyOnSpecialOrder = qtyOnSpecialOrder;
    return this;
  }

   /**
   * Get qtyOnSpecialOrder
   * @return qtyOnSpecialOrder
  **/
  @ApiModelProperty(value = "")
  public String getQtyOnSpecialOrder() {
    return qtyOnSpecialOrder;
  }

  public void setQtyOnSpecialOrder(String qtyOnSpecialOrder) {
    this.qtyOnSpecialOrder = qtyOnSpecialOrder;
  }

  public FSOrderLine qtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
    return this;
  }

   /**
   * Get qtyOrdered
   * @return qtyOrdered
  **/
  @ApiModelProperty(value = "")
  public String getQtyOrdered() {
    return qtyOrdered;
  }

  public void setQtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
  }

  public FSOrderLine releaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public String getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(String releaseDate) {
    this.releaseDate = releaseDate;
  }

  public FSOrderLine uom(String uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @ApiModelProperty(value = "")
  public String getUom() {
    return uom;
  }

  public void setUom(String uom) {
    this.uom = uom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FSOrderLine fsOrderLine = (FSOrderLine) o;
    return Objects.equals(this.bundle, fsOrderLine.bundle) &&
        Objects.equals(this.configureToOrderID, fsOrderLine.configureToOrderID) &&
        Objects.equals(this.etaDate, fsOrderLine.etaDate) &&
        Objects.equals(this.fsolStatus, fsOrderLine.fsolStatus) &&
        Objects.equals(this.id, fsOrderLine.id) &&
        Objects.equals(this.itemCharge, fsOrderLine.itemCharge) &&
        Objects.equals(this.linenum, fsOrderLine.linenum) &&
        Objects.equals(this.product, fsOrderLine.product) &&
        Objects.equals(this.pspcoveredFSOrderlineID, fsOrderLine.pspcoveredFSOrderlineID) &&
        Objects.equals(this.qtyCancelled, fsOrderLine.qtyCancelled) &&
        Objects.equals(this.qtyOnSpecialOrder, fsOrderLine.qtyOnSpecialOrder) &&
        Objects.equals(this.qtyOrdered, fsOrderLine.qtyOrdered) &&
        Objects.equals(this.releaseDate, fsOrderLine.releaseDate) &&
        Objects.equals(this.uom, fsOrderLine.uom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundle, configureToOrderID, etaDate, fsolStatus, id, itemCharge, linenum, product, pspcoveredFSOrderlineID, qtyCancelled, qtyOnSpecialOrder, qtyOrdered, releaseDate, uom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FSOrderLine {\n");
    
    sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
    sb.append("    configureToOrderID: ").append(toIndentedString(configureToOrderID)).append("\n");
    sb.append("    etaDate: ").append(toIndentedString(etaDate)).append("\n");
    sb.append("    fsolStatus: ").append(toIndentedString(fsolStatus)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemCharge: ").append(toIndentedString(itemCharge)).append("\n");
    sb.append("    linenum: ").append(toIndentedString(linenum)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    pspcoveredFSOrderlineID: ").append(toIndentedString(pspcoveredFSOrderlineID)).append("\n");
    sb.append("    qtyCancelled: ").append(toIndentedString(qtyCancelled)).append("\n");
    sb.append("    qtyOnSpecialOrder: ").append(toIndentedString(qtyOnSpecialOrder)).append("\n");
    sb.append("    qtyOrdered: ").append(toIndentedString(qtyOrdered)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

