/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GiftCard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class GiftCard {
  @JsonProperty("giftCardNumber")
  private Integer giftCardNumber = null;

  @JsonProperty("giftCardType")
  private String giftCardType = null;

  @JsonProperty("secureCode")
  private String secureCode = null;

  public GiftCard giftCardNumber(Integer giftCardNumber) {
    this.giftCardNumber = giftCardNumber;
    return this;
  }

   /**
   * Get giftCardNumber
   * @return giftCardNumber
  **/
  @ApiModelProperty(value = "")
  public Integer getGiftCardNumber() {
    return giftCardNumber;
  }

  public void setGiftCardNumber(Integer giftCardNumber) {
    this.giftCardNumber = giftCardNumber;
  }

  public GiftCard giftCardType(String giftCardType) {
    this.giftCardType = giftCardType;
    return this;
  }

   /**
   * Get giftCardType
   * @return giftCardType
  **/
  @ApiModelProperty(value = "")
  public String getGiftCardType() {
    return giftCardType;
  }

  public void setGiftCardType(String giftCardType) {
    this.giftCardType = giftCardType;
  }

  public GiftCard secureCode(String secureCode) {
    this.secureCode = secureCode;
    return this;
  }

   /**
   * Get secureCode
   * @return secureCode
  **/
  @ApiModelProperty(value = "")
  public String getSecureCode() {
    return secureCode;
  }

  public void setSecureCode(String secureCode) {
    this.secureCode = secureCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCard giftCard = (GiftCard) o;
    return Objects.equals(this.giftCardNumber, giftCard.giftCardNumber) &&
        Objects.equals(this.giftCardType, giftCard.giftCardType) &&
        Objects.equals(this.secureCode, giftCard.secureCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(giftCardNumber, giftCardType, secureCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCard {\n");
    
    sb.append("    giftCardNumber: ").append(toIndentedString(giftCardNumber)).append("\n");
    sb.append("    giftCardType: ").append(toIndentedString(giftCardType)).append("\n");
    sb.append("    secureCode: ").append(toIndentedString(secureCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

