/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetailsservice.CreditCardPaymentMethod;
import com.bbyc.orders.model.client.orderdetailsservice.GiftCardPaymentMethod;
import com.bbyc.orders.model.client.orderdetailsservice.POSPaymentMethod;
import com.bbyc.orders.model.client.orderdetailsservice.PayPalPaymentMethod;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PaymentMethodList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class PaymentMethodList {
  @JsonProperty("creditCardPaymentMethods")
  private List<CreditCardPaymentMethod> creditCardPaymentMethods = null;

  @JsonProperty("editable")
  private String editable = null;

  @JsonProperty("giftCardPaymentMethods")
  private List<GiftCardPaymentMethod> giftCardPaymentMethods = null;

  @JsonProperty("payPalPaymentMethods")
  private List<PayPalPaymentMethod> payPalPaymentMethods = null;

  @JsonProperty("posPaymentMethods")
  private List<POSPaymentMethod> posPaymentMethods = null;

  public PaymentMethodList creditCardPaymentMethods(List<CreditCardPaymentMethod> creditCardPaymentMethods) {
    this.creditCardPaymentMethods = creditCardPaymentMethods;
    return this;
  }

  public PaymentMethodList addCreditCardPaymentMethodsItem(CreditCardPaymentMethod creditCardPaymentMethodsItem) {
    if (this.creditCardPaymentMethods == null) {
      this.creditCardPaymentMethods = new ArrayList<CreditCardPaymentMethod>();
    }
    this.creditCardPaymentMethods.add(creditCardPaymentMethodsItem);
    return this;
  }

   /**
   * Get creditCardPaymentMethods
   * @return creditCardPaymentMethods
  **/
  @ApiModelProperty(value = "")
  public List<CreditCardPaymentMethod> getCreditCardPaymentMethods() {
    return creditCardPaymentMethods;
  }

  public void setCreditCardPaymentMethods(List<CreditCardPaymentMethod> creditCardPaymentMethods) {
    this.creditCardPaymentMethods = creditCardPaymentMethods;
  }

  public PaymentMethodList editable(String editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Get editable
   * @return editable
  **/
  @ApiModelProperty(value = "")
  public String getEditable() {
    return editable;
  }

  public void setEditable(String editable) {
    this.editable = editable;
  }

  public PaymentMethodList giftCardPaymentMethods(List<GiftCardPaymentMethod> giftCardPaymentMethods) {
    this.giftCardPaymentMethods = giftCardPaymentMethods;
    return this;
  }

  public PaymentMethodList addGiftCardPaymentMethodsItem(GiftCardPaymentMethod giftCardPaymentMethodsItem) {
    if (this.giftCardPaymentMethods == null) {
      this.giftCardPaymentMethods = new ArrayList<GiftCardPaymentMethod>();
    }
    this.giftCardPaymentMethods.add(giftCardPaymentMethodsItem);
    return this;
  }

   /**
   * Get giftCardPaymentMethods
   * @return giftCardPaymentMethods
  **/
  @ApiModelProperty(value = "")
  public List<GiftCardPaymentMethod> getGiftCardPaymentMethods() {
    return giftCardPaymentMethods;
  }

  public void setGiftCardPaymentMethods(List<GiftCardPaymentMethod> giftCardPaymentMethods) {
    this.giftCardPaymentMethods = giftCardPaymentMethods;
  }

  public PaymentMethodList payPalPaymentMethods(List<PayPalPaymentMethod> payPalPaymentMethods) {
    this.payPalPaymentMethods = payPalPaymentMethods;
    return this;
  }

  public PaymentMethodList addPayPalPaymentMethodsItem(PayPalPaymentMethod payPalPaymentMethodsItem) {
    if (this.payPalPaymentMethods == null) {
      this.payPalPaymentMethods = new ArrayList<PayPalPaymentMethod>();
    }
    this.payPalPaymentMethods.add(payPalPaymentMethodsItem);
    return this;
  }

   /**
   * Get payPalPaymentMethods
   * @return payPalPaymentMethods
  **/
  @ApiModelProperty(value = "")
  public List<PayPalPaymentMethod> getPayPalPaymentMethods() {
    return payPalPaymentMethods;
  }

  public void setPayPalPaymentMethods(List<PayPalPaymentMethod> payPalPaymentMethods) {
    this.payPalPaymentMethods = payPalPaymentMethods;
  }

  public PaymentMethodList posPaymentMethods(List<POSPaymentMethod> posPaymentMethods) {
    this.posPaymentMethods = posPaymentMethods;
    return this;
  }

  public PaymentMethodList addPosPaymentMethodsItem(POSPaymentMethod posPaymentMethodsItem) {
    if (this.posPaymentMethods == null) {
      this.posPaymentMethods = new ArrayList<POSPaymentMethod>();
    }
    this.posPaymentMethods.add(posPaymentMethodsItem);
    return this;
  }

   /**
   * Get posPaymentMethods
   * @return posPaymentMethods
  **/
  @ApiModelProperty(value = "")
  public List<POSPaymentMethod> getPosPaymentMethods() {
    return posPaymentMethods;
  }

  public void setPosPaymentMethods(List<POSPaymentMethod> posPaymentMethods) {
    this.posPaymentMethods = posPaymentMethods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodList paymentMethodList = (PaymentMethodList) o;
    return Objects.equals(this.creditCardPaymentMethods, paymentMethodList.creditCardPaymentMethods) &&
        Objects.equals(this.editable, paymentMethodList.editable) &&
        Objects.equals(this.giftCardPaymentMethods, paymentMethodList.giftCardPaymentMethods) &&
        Objects.equals(this.payPalPaymentMethods, paymentMethodList.payPalPaymentMethods) &&
        Objects.equals(this.posPaymentMethods, paymentMethodList.posPaymentMethods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCardPaymentMethods, editable, giftCardPaymentMethods, payPalPaymentMethods, posPaymentMethods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodList {\n");
    
    sb.append("    creditCardPaymentMethods: ").append(toIndentedString(creditCardPaymentMethods)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    giftCardPaymentMethods: ").append(toIndentedString(giftCardPaymentMethods)).append("\n");
    sb.append("    payPalPaymentMethods: ").append(toIndentedString(payPalPaymentMethods)).append("\n");
    sb.append("    posPaymentMethods: ").append(toIndentedString(posPaymentMethods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

