/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Paypal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class Paypal {
  @JsonProperty("paymentRefId")
  private String paymentRefId = null;

  public Paypal paymentRefId(String paymentRefId) {
    this.paymentRefId = paymentRefId;
    return this;
  }

   /**
   * Get paymentRefId
   * @return paymentRefId
  **/
  @ApiModelProperty(value = "")
  public String getPaymentRefId() {
    return paymentRefId;
  }

  public void setPaymentRefId(String paymentRefId) {
    this.paymentRefId = paymentRefId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Paypal paypal = (Paypal) o;
    return Objects.equals(this.paymentRefId, paypal.paymentRefId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentRefId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Paypal {\n");
    
    sb.append("    paymentRefId: ").append(toIndentedString(paymentRefId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

