/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetailsservice.FulfillmentLocationIdentifier;
import com.bbyc.orders.model.client.orderdetailsservice.FulfillmentPartnerProductType;
import com.bbyc.orders.model.client.orderdetailsservice.StringEditableType;
import com.bbyc.orders.model.client.orderdetailsservice.XMLGregorianCalendar;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PurchaseOrderLine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class PurchaseOrderLine {
  @JsonProperty("availability")
  private String availability = null;

  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("deliveryDate")
  private XMLGregorianCalendar deliveryDate = null;

  @JsonProperty("eta")
  private XMLGregorianCalendar eta = null;

  @JsonProperty("ffpPOlineNo")
  private StringEditableType ffpPOlineNo = null;

  @JsonProperty("ffpProduct")
  private FulfillmentPartnerProductType ffpProduct = null;

  @JsonProperty("fsoLineID")
  private String fsoLineID = null;

  @JsonProperty("fulfillmentLocationIdentifier")
  private FulfillmentLocationIdentifier fulfillmentLocationIdentifier = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("qtyAllocated")
  private StringEditableType qtyAllocated = null;

  @JsonProperty("qtyBackOrder")
  private StringEditableType qtyBackOrder = null;

  @JsonProperty("qtyOrdered")
  private String qtyOrdered = null;

  @JsonProperty("releaseDate")
  private XMLGregorianCalendar releaseDate = null;

  @JsonProperty("shippingOrderLineID")
  private String shippingOrderLineID = null;

  public PurchaseOrderLine availability(String availability) {
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @ApiModelProperty(value = "")
  public String getAvailability() {
    return availability;
  }

  public void setAvailability(String availability) {
    this.availability = availability;
  }

  public PurchaseOrderLine comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public PurchaseOrderLine deliveryDate(XMLGregorianCalendar deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  @ApiModelProperty(value = "")
  public XMLGregorianCalendar getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(XMLGregorianCalendar deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public PurchaseOrderLine eta(XMLGregorianCalendar eta) {
    this.eta = eta;
    return this;
  }

   /**
   * Get eta
   * @return eta
  **/
  @ApiModelProperty(value = "")
  public XMLGregorianCalendar getEta() {
    return eta;
  }

  public void setEta(XMLGregorianCalendar eta) {
    this.eta = eta;
  }

  public PurchaseOrderLine ffpPOlineNo(StringEditableType ffpPOlineNo) {
    this.ffpPOlineNo = ffpPOlineNo;
    return this;
  }

   /**
   * Get ffpPOlineNo
   * @return ffpPOlineNo
  **/
  @ApiModelProperty(value = "")
  public StringEditableType getFfpPOlineNo() {
    return ffpPOlineNo;
  }

  public void setFfpPOlineNo(StringEditableType ffpPOlineNo) {
    this.ffpPOlineNo = ffpPOlineNo;
  }

  public PurchaseOrderLine ffpProduct(FulfillmentPartnerProductType ffpProduct) {
    this.ffpProduct = ffpProduct;
    return this;
  }

   /**
   * Get ffpProduct
   * @return ffpProduct
  **/
  @ApiModelProperty(value = "")
  public FulfillmentPartnerProductType getFfpProduct() {
    return ffpProduct;
  }

  public void setFfpProduct(FulfillmentPartnerProductType ffpProduct) {
    this.ffpProduct = ffpProduct;
  }

  public PurchaseOrderLine fsoLineID(String fsoLineID) {
    this.fsoLineID = fsoLineID;
    return this;
  }

   /**
   * Get fsoLineID
   * @return fsoLineID
  **/
  @ApiModelProperty(value = "")
  public String getFsoLineID() {
    return fsoLineID;
  }

  public void setFsoLineID(String fsoLineID) {
    this.fsoLineID = fsoLineID;
  }

  public PurchaseOrderLine fulfillmentLocationIdentifier(FulfillmentLocationIdentifier fulfillmentLocationIdentifier) {
    this.fulfillmentLocationIdentifier = fulfillmentLocationIdentifier;
    return this;
  }

   /**
   * Get fulfillmentLocationIdentifier
   * @return fulfillmentLocationIdentifier
  **/
  @ApiModelProperty(value = "")
  public FulfillmentLocationIdentifier getFulfillmentLocationIdentifier() {
    return fulfillmentLocationIdentifier;
  }

  public void setFulfillmentLocationIdentifier(FulfillmentLocationIdentifier fulfillmentLocationIdentifier) {
    this.fulfillmentLocationIdentifier = fulfillmentLocationIdentifier;
  }

  public PurchaseOrderLine id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PurchaseOrderLine qtyAllocated(StringEditableType qtyAllocated) {
    this.qtyAllocated = qtyAllocated;
    return this;
  }

   /**
   * Get qtyAllocated
   * @return qtyAllocated
  **/
  @ApiModelProperty(value = "")
  public StringEditableType getQtyAllocated() {
    return qtyAllocated;
  }

  public void setQtyAllocated(StringEditableType qtyAllocated) {
    this.qtyAllocated = qtyAllocated;
  }

  public PurchaseOrderLine qtyBackOrder(StringEditableType qtyBackOrder) {
    this.qtyBackOrder = qtyBackOrder;
    return this;
  }

   /**
   * Get qtyBackOrder
   * @return qtyBackOrder
  **/
  @ApiModelProperty(value = "")
  public StringEditableType getQtyBackOrder() {
    return qtyBackOrder;
  }

  public void setQtyBackOrder(StringEditableType qtyBackOrder) {
    this.qtyBackOrder = qtyBackOrder;
  }

  public PurchaseOrderLine qtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
    return this;
  }

   /**
   * Get qtyOrdered
   * @return qtyOrdered
  **/
  @ApiModelProperty(value = "")
  public String getQtyOrdered() {
    return qtyOrdered;
  }

  public void setQtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
  }

  public PurchaseOrderLine releaseDate(XMLGregorianCalendar releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public XMLGregorianCalendar getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(XMLGregorianCalendar releaseDate) {
    this.releaseDate = releaseDate;
  }

  public PurchaseOrderLine shippingOrderLineID(String shippingOrderLineID) {
    this.shippingOrderLineID = shippingOrderLineID;
    return this;
  }

   /**
   * Get shippingOrderLineID
   * @return shippingOrderLineID
  **/
  @ApiModelProperty(value = "")
  public String getShippingOrderLineID() {
    return shippingOrderLineID;
  }

  public void setShippingOrderLineID(String shippingOrderLineID) {
    this.shippingOrderLineID = shippingOrderLineID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrderLine purchaseOrderLine = (PurchaseOrderLine) o;
    return Objects.equals(this.availability, purchaseOrderLine.availability) &&
        Objects.equals(this.comments, purchaseOrderLine.comments) &&
        Objects.equals(this.deliveryDate, purchaseOrderLine.deliveryDate) &&
        Objects.equals(this.eta, purchaseOrderLine.eta) &&
        Objects.equals(this.ffpPOlineNo, purchaseOrderLine.ffpPOlineNo) &&
        Objects.equals(this.ffpProduct, purchaseOrderLine.ffpProduct) &&
        Objects.equals(this.fsoLineID, purchaseOrderLine.fsoLineID) &&
        Objects.equals(this.fulfillmentLocationIdentifier, purchaseOrderLine.fulfillmentLocationIdentifier) &&
        Objects.equals(this.id, purchaseOrderLine.id) &&
        Objects.equals(this.qtyAllocated, purchaseOrderLine.qtyAllocated) &&
        Objects.equals(this.qtyBackOrder, purchaseOrderLine.qtyBackOrder) &&
        Objects.equals(this.qtyOrdered, purchaseOrderLine.qtyOrdered) &&
        Objects.equals(this.releaseDate, purchaseOrderLine.releaseDate) &&
        Objects.equals(this.shippingOrderLineID, purchaseOrderLine.shippingOrderLineID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availability, comments, deliveryDate, eta, ffpPOlineNo, ffpProduct, fsoLineID, fulfillmentLocationIdentifier, id, qtyAllocated, qtyBackOrder, qtyOrdered, releaseDate, shippingOrderLineID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrderLine {\n");
    
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    ffpPOlineNo: ").append(toIndentedString(ffpPOlineNo)).append("\n");
    sb.append("    ffpProduct: ").append(toIndentedString(ffpProduct)).append("\n");
    sb.append("    fsoLineID: ").append(toIndentedString(fsoLineID)).append("\n");
    sb.append("    fulfillmentLocationIdentifier: ").append(toIndentedString(fulfillmentLocationIdentifier)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    qtyAllocated: ").append(toIndentedString(qtyAllocated)).append("\n");
    sb.append("    qtyBackOrder: ").append(toIndentedString(qtyBackOrder)).append("\n");
    sb.append("    qtyOrdered: ").append(toIndentedString(qtyOrdered)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    shippingOrderLineID: ").append(toIndentedString(shippingOrderLineID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

