/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PurchaseOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class PurchaseOrder {
  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("creationDate")
  private String creationDate = null;

  @JsonProperty("ffpId")
  private String ffpId = null;

  @JsonProperty("ffpPoNo")
  private StringEditableType ffpPoNo = null;

  @JsonProperty("fulfillmentPartner")
  private List<FulfillmentPartnerType> fulfillmentPartner = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("orderDate")
  private String orderDate = null;

  @JsonProperty("poSendStatus")
  private PoSendStatus poSendStatus = null;

  @JsonProperty("purchaseOrderLine")
  private List<PurchaseOrderLine> purchaseOrderLine = null;

  @JsonProperty("shippingOrderID")
  private String shippingOrderID = null;

  public PurchaseOrder comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public PurchaseOrder creationDate(String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public String getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(String creationDate) {
    this.creationDate = creationDate;
  }

  public PurchaseOrder ffpId(String ffpId) {
    this.ffpId = ffpId;
    return this;
  }

   /**
   * Get ffpId
   * @return ffpId
  **/
  @ApiModelProperty(value = "")
  public String getFfpId() {
    return ffpId;
  }

  public void setFfpId(String ffpId) {
    this.ffpId = ffpId;
  }

  public PurchaseOrder ffpPoNo(StringEditableType ffpPoNo) {
    this.ffpPoNo = ffpPoNo;
    return this;
  }

   /**
   * Get ffpPoNo
   * @return ffpPoNo
  **/
  @ApiModelProperty(value = "")
  public StringEditableType getFfpPoNo() {
    return ffpPoNo;
  }

  public void setFfpPoNo(StringEditableType ffpPoNo) {
    this.ffpPoNo = ffpPoNo;
  }

  public PurchaseOrder fulfillmentPartner(List<FulfillmentPartnerType> fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
    return this;
  }

  public PurchaseOrder addFulfillmentPartnerItem(FulfillmentPartnerType fulfillmentPartnerItem) {
    if (this.fulfillmentPartner == null) {
      this.fulfillmentPartner = new ArrayList<FulfillmentPartnerType>();
    }
    this.fulfillmentPartner.add(fulfillmentPartnerItem);
    return this;
  }

   /**
   * Get fulfillmentPartner
   * @return fulfillmentPartner
  **/
  @ApiModelProperty(value = "")
  public List<FulfillmentPartnerType> getFulfillmentPartner() {
    return fulfillmentPartner;
  }

  public void setFulfillmentPartner(List<FulfillmentPartnerType> fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
  }

  public PurchaseOrder id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PurchaseOrder orderDate(String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  @ApiModelProperty(value = "")
  public String getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(String orderDate) {
    this.orderDate = orderDate;
  }

  public PurchaseOrder poSendStatus(PoSendStatus poSendStatus) {
    this.poSendStatus = poSendStatus;
    return this;
  }

   /**
   * Get poSendStatus
   * @return poSendStatus
  **/
  @ApiModelProperty(value = "")
  public PoSendStatus getPoSendStatus() {
    return poSendStatus;
  }

  public void setPoSendStatus(PoSendStatus poSendStatus) {
    this.poSendStatus = poSendStatus;
  }

  public PurchaseOrder purchaseOrderLine(List<PurchaseOrderLine> purchaseOrderLine) {
    this.purchaseOrderLine = purchaseOrderLine;
    return this;
  }

  public PurchaseOrder addPurchaseOrderLineItem(PurchaseOrderLine purchaseOrderLineItem) {
    if (this.purchaseOrderLine == null) {
      this.purchaseOrderLine = new ArrayList<PurchaseOrderLine>();
    }
    this.purchaseOrderLine.add(purchaseOrderLineItem);
    return this;
  }

   /**
   * Get purchaseOrderLine
   * @return purchaseOrderLine
  **/
  @ApiModelProperty(value = "")
  public List<PurchaseOrderLine> getPurchaseOrderLine() {
    return purchaseOrderLine;
  }

  public void setPurchaseOrderLine(List<PurchaseOrderLine> purchaseOrderLine) {
    this.purchaseOrderLine = purchaseOrderLine;
  }

  public PurchaseOrder shippingOrderID(String shippingOrderID) {
    this.shippingOrderID = shippingOrderID;
    return this;
  }

   /**
   * Get shippingOrderID
   * @return shippingOrderID
  **/
  @ApiModelProperty(value = "")
  public String getShippingOrderID() {
    return shippingOrderID;
  }

  public void setShippingOrderID(String shippingOrderID) {
    this.shippingOrderID = shippingOrderID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrder purchaseOrder = (PurchaseOrder) o;
    return Objects.equals(this.comments, purchaseOrder.comments) &&
        Objects.equals(this.creationDate, purchaseOrder.creationDate) &&
        Objects.equals(this.ffpId, purchaseOrder.ffpId) &&
        Objects.equals(this.ffpPoNo, purchaseOrder.ffpPoNo) &&
        Objects.equals(this.fulfillmentPartner, purchaseOrder.fulfillmentPartner) &&
        Objects.equals(this.id, purchaseOrder.id) &&
        Objects.equals(this.orderDate, purchaseOrder.orderDate) &&
        Objects.equals(this.poSendStatus, purchaseOrder.poSendStatus) &&
        Objects.equals(this.purchaseOrderLine, purchaseOrder.purchaseOrderLine) &&
        Objects.equals(this.shippingOrderID, purchaseOrder.shippingOrderID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comments, creationDate, ffpId, ffpPoNo, fulfillmentPartner, id, orderDate, poSendStatus, purchaseOrderLine, shippingOrderID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrder {\n");
    
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    ffpId: ").append(toIndentedString(ffpId)).append("\n");
    sb.append("    ffpPoNo: ").append(toIndentedString(ffpPoNo)).append("\n");
    sb.append("    fulfillmentPartner: ").append(toIndentedString(fulfillmentPartner)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    poSendStatus: ").append(toIndentedString(poSendStatus)).append("\n");
    sb.append("    purchaseOrderLine: ").append(toIndentedString(purchaseOrderLine)).append("\n");
    sb.append("    shippingOrderID: ").append(toIndentedString(shippingOrderID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

