/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RewardZoneCard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class RewardZoneCard {
  @JsonProperty("editable")
  private String editable = null;

  @JsonProperty("rewardZoneID")
  private RewardZoneID rewardZoneID = null;

  public RewardZoneCard editable(String editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Get editable
   * @return editable
  **/
  @ApiModelProperty(value = "")
  public String getEditable() {
    return editable;
  }

  public void setEditable(String editable) {
    this.editable = editable;
  }

  public RewardZoneCard rewardZoneID(RewardZoneID rewardZoneID) {
    this.rewardZoneID = rewardZoneID;
    return this;
  }

   /**
   * Get rewardZoneID
   * @return rewardZoneID
  **/
  @ApiModelProperty(value = "")
  public RewardZoneID getRewardZoneID() {
    return rewardZoneID;
  }

  public void setRewardZoneID(RewardZoneID rewardZoneID) {
    this.rewardZoneID = rewardZoneID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardZoneCard rewardZoneCard = (RewardZoneCard) o;
    return Objects.equals(this.editable, rewardZoneCard.editable) &&
        Objects.equals(this.rewardZoneID, rewardZoneCard.rewardZoneID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(editable, rewardZoneID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardZoneCard {\n");
    
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    rewardZoneID: ").append(toIndentedString(rewardZoneID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

