/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RewardZone
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class RewardZone {
  @JsonProperty("rewardZoneCard")
  private RewardZoneCard rewardZoneCard = null;

  public RewardZone rewardZoneCard(RewardZoneCard rewardZoneCard) {
    this.rewardZoneCard = rewardZoneCard;
    return this;
  }

   /**
   * Get rewardZoneCard
   * @return rewardZoneCard
  **/
  @ApiModelProperty(value = "")
  public RewardZoneCard getRewardZoneCard() {
    return rewardZoneCard;
  }

  public void setRewardZoneCard(RewardZoneCard rewardZoneCard) {
    this.rewardZoneCard = rewardZoneCard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RewardZone rewardZone = (RewardZone) o;
    return Objects.equals(this.rewardZoneCard, rewardZone.rewardZoneCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rewardZoneCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RewardZone {\n");
    
    sb.append("    rewardZoneCard: ").append(toIndentedString(rewardZoneCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

