/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetailsservice.ActualCarrier;
import com.bbyc.orders.model.client.orderdetailsservice.PaymentInfo;
import com.bbyc.orders.model.client.orderdetailsservice.RequestedCarrier;
import com.bbyc.orders.model.client.orderdetailsservice.RequestedDeliveryDate;
import com.bbyc.orders.model.client.orderdetailsservice.ShipAddrInfo;
import com.bbyc.orders.model.client.orderdetailsservice.ShipFromAddrInfo;
import com.bbyc.orders.model.client.orderdetailsservice.ShippingCharge;
import com.bbyc.orders.model.client.orderdetailsservice.ShippingOrderLine;
import com.bbyc.orders.model.client.orderdetailsservice.ShippingStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ShippingOrder
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class ShippingOrder {
  @JsonProperty("actualCarrier")
  private ActualCarrier actualCarrier = null;

  @JsonProperty("createdBy")
  private String createdBy = null;

  @JsonProperty("fulfillmentMethod")
  private String fulfillmentMethod = null;

  @JsonProperty("fulfillmentPartner")
  private String fulfillmentPartner = null;

  @JsonProperty("globalContractId")
  private String globalContractId = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("isCustomerInvoiceAvailable")
  private String isCustomerInvoiceAvailable = null;

  @JsonProperty("paymentInfo")
  private PaymentInfo paymentInfo = null;

  @JsonProperty("requestedCarrier")
  private RequestedCarrier requestedCarrier = null;

  @JsonProperty("requestedDeliveryDate")
  private RequestedDeliveryDate requestedDeliveryDate = null;

  @JsonProperty("shipAddrInfo")
  private ShipAddrInfo shipAddrInfo = null;

  @JsonProperty("shipFromAddrInfo")
  private ShipFromAddrInfo shipFromAddrInfo = null;

  @JsonProperty("shipmentDate")
  private String shipmentDate = null;

  @JsonProperty("shippingCharge")
  private List<ShippingCharge> shippingCharge = null;

  @JsonProperty("shippingOrderLine")
  private List<ShippingOrderLine> shippingOrderLine = null;

  @JsonProperty("shippingStatus")
  private ShippingStatus shippingStatus = null;

  @JsonProperty("storeToFulfillFrom")
  private String storeToFulfillFrom = null;

  @JsonProperty("type")
  private String type = null;

  public ShippingOrder actualCarrier(ActualCarrier actualCarrier) {
    this.actualCarrier = actualCarrier;
    return this;
  }

   /**
   * Get actualCarrier
   * @return actualCarrier
  **/
  @ApiModelProperty(value = "")
  public ActualCarrier getActualCarrier() {
    return actualCarrier;
  }

  public void setActualCarrier(ActualCarrier actualCarrier) {
    this.actualCarrier = actualCarrier;
  }

  public ShippingOrder createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ShippingOrder fulfillmentMethod(String fulfillmentMethod) {
    this.fulfillmentMethod = fulfillmentMethod;
    return this;
  }

   /**
   * Get fulfillmentMethod
   * @return fulfillmentMethod
  **/
  @ApiModelProperty(value = "")
  public String getFulfillmentMethod() {
    return fulfillmentMethod;
  }

  public void setFulfillmentMethod(String fulfillmentMethod) {
    this.fulfillmentMethod = fulfillmentMethod;
  }

  public ShippingOrder fulfillmentPartner(String fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
    return this;
  }

   /**
   * Get fulfillmentPartner
   * @return fulfillmentPartner
  **/
  @ApiModelProperty(value = "")
  public String getFulfillmentPartner() {
    return fulfillmentPartner;
  }

  public void setFulfillmentPartner(String fulfillmentPartner) {
    this.fulfillmentPartner = fulfillmentPartner;
  }

  public ShippingOrder globalContractId(String globalContractId) {
    this.globalContractId = globalContractId;
    return this;
  }

   /**
   * Get globalContractId
   * @return globalContractId
  **/
  @ApiModelProperty(value = "")
  public String getGlobalContractId() {
    return globalContractId;
  }

  public void setGlobalContractId(String globalContractId) {
    this.globalContractId = globalContractId;
  }

  public ShippingOrder id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ShippingOrder isCustomerInvoiceAvailable(String isCustomerInvoiceAvailable) {
    this.isCustomerInvoiceAvailable = isCustomerInvoiceAvailable;
    return this;
  }

   /**
   * Get isCustomerInvoiceAvailable
   * @return isCustomerInvoiceAvailable
  **/
  @ApiModelProperty(value = "")
  public String getIsCustomerInvoiceAvailable() {
    return isCustomerInvoiceAvailable;
  }

  public void setIsCustomerInvoiceAvailable(String isCustomerInvoiceAvailable) {
    this.isCustomerInvoiceAvailable = isCustomerInvoiceAvailable;
  }

  public ShippingOrder paymentInfo(PaymentInfo paymentInfo) {
    this.paymentInfo = paymentInfo;
    return this;
  }

   /**
   * Get paymentInfo
   * @return paymentInfo
  **/
  @ApiModelProperty(value = "")
  public PaymentInfo getPaymentInfo() {
    return paymentInfo;
  }

  public void setPaymentInfo(PaymentInfo paymentInfo) {
    this.paymentInfo = paymentInfo;
  }

  public ShippingOrder requestedCarrier(RequestedCarrier requestedCarrier) {
    this.requestedCarrier = requestedCarrier;
    return this;
  }

   /**
   * Get requestedCarrier
   * @return requestedCarrier
  **/
  @ApiModelProperty(value = "")
  public RequestedCarrier getRequestedCarrier() {
    return requestedCarrier;
  }

  public void setRequestedCarrier(RequestedCarrier requestedCarrier) {
    this.requestedCarrier = requestedCarrier;
  }

  public ShippingOrder requestedDeliveryDate(RequestedDeliveryDate requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
    return this;
  }

   /**
   * Get requestedDeliveryDate
   * @return requestedDeliveryDate
  **/
  @ApiModelProperty(value = "")
  public RequestedDeliveryDate getRequestedDeliveryDate() {
    return requestedDeliveryDate;
  }

  public void setRequestedDeliveryDate(RequestedDeliveryDate requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
  }

  public ShippingOrder shipAddrInfo(ShipAddrInfo shipAddrInfo) {
    this.shipAddrInfo = shipAddrInfo;
    return this;
  }

   /**
   * Get shipAddrInfo
   * @return shipAddrInfo
  **/
  @ApiModelProperty(value = "")
  public ShipAddrInfo getShipAddrInfo() {
    return shipAddrInfo;
  }

  public void setShipAddrInfo(ShipAddrInfo shipAddrInfo) {
    this.shipAddrInfo = shipAddrInfo;
  }

  public ShippingOrder shipFromAddrInfo(ShipFromAddrInfo shipFromAddrInfo) {
    this.shipFromAddrInfo = shipFromAddrInfo;
    return this;
  }

   /**
   * Get shipFromAddrInfo
   * @return shipFromAddrInfo
  **/
  @ApiModelProperty(value = "")
  public ShipFromAddrInfo getShipFromAddrInfo() {
    return shipFromAddrInfo;
  }

  public void setShipFromAddrInfo(ShipFromAddrInfo shipFromAddrInfo) {
    this.shipFromAddrInfo = shipFromAddrInfo;
  }

  public ShippingOrder shipmentDate(String shipmentDate) {
    this.shipmentDate = shipmentDate;
    return this;
  }

   /**
   * Get shipmentDate
   * @return shipmentDate
  **/
  @ApiModelProperty(value = "")
  public String getShipmentDate() {
    return shipmentDate;
  }

  public void setShipmentDate(String shipmentDate) {
    this.shipmentDate = shipmentDate;
  }

  public ShippingOrder shippingCharge(List<ShippingCharge> shippingCharge) {
    this.shippingCharge = shippingCharge;
    return this;
  }

  public ShippingOrder addShippingChargeItem(ShippingCharge shippingChargeItem) {
    if (this.shippingCharge == null) {
      this.shippingCharge = new ArrayList<ShippingCharge>();
    }
    this.shippingCharge.add(shippingChargeItem);
    return this;
  }

   /**
   * Get shippingCharge
   * @return shippingCharge
  **/
  @ApiModelProperty(value = "")
  public List<ShippingCharge> getShippingCharge() {
    return shippingCharge;
  }

  public void setShippingCharge(List<ShippingCharge> shippingCharge) {
    this.shippingCharge = shippingCharge;
  }

  public ShippingOrder shippingOrderLine(List<ShippingOrderLine> shippingOrderLine) {
    this.shippingOrderLine = shippingOrderLine;
    return this;
  }

  public ShippingOrder addShippingOrderLineItem(ShippingOrderLine shippingOrderLineItem) {
    if (this.shippingOrderLine == null) {
      this.shippingOrderLine = new ArrayList<ShippingOrderLine>();
    }
    this.shippingOrderLine.add(shippingOrderLineItem);
    return this;
  }

   /**
   * Get shippingOrderLine
   * @return shippingOrderLine
  **/
  @ApiModelProperty(value = "")
  public List<ShippingOrderLine> getShippingOrderLine() {
    return shippingOrderLine;
  }

  public void setShippingOrderLine(List<ShippingOrderLine> shippingOrderLine) {
    this.shippingOrderLine = shippingOrderLine;
  }

  public ShippingOrder shippingStatus(ShippingStatus shippingStatus) {
    this.shippingStatus = shippingStatus;
    return this;
  }

   /**
   * Get shippingStatus
   * @return shippingStatus
  **/
  @ApiModelProperty(value = "")
  public ShippingStatus getShippingStatus() {
    return shippingStatus;
  }

  public void setShippingStatus(ShippingStatus shippingStatus) {
    this.shippingStatus = shippingStatus;
  }

  public ShippingOrder storeToFulfillFrom(String storeToFulfillFrom) {
    this.storeToFulfillFrom = storeToFulfillFrom;
    return this;
  }

   /**
   * Get storeToFulfillFrom
   * @return storeToFulfillFrom
  **/
  @ApiModelProperty(value = "")
  public String getStoreToFulfillFrom() {
    return storeToFulfillFrom;
  }

  public void setStoreToFulfillFrom(String storeToFulfillFrom) {
    this.storeToFulfillFrom = storeToFulfillFrom;
  }

  public ShippingOrder type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingOrder shippingOrder = (ShippingOrder) o;
    return Objects.equals(this.actualCarrier, shippingOrder.actualCarrier) &&
        Objects.equals(this.createdBy, shippingOrder.createdBy) &&
        Objects.equals(this.fulfillmentMethod, shippingOrder.fulfillmentMethod) &&
        Objects.equals(this.fulfillmentPartner, shippingOrder.fulfillmentPartner) &&
        Objects.equals(this.globalContractId, shippingOrder.globalContractId) &&
        Objects.equals(this.id, shippingOrder.id) &&
        Objects.equals(this.isCustomerInvoiceAvailable, shippingOrder.isCustomerInvoiceAvailable) &&
        Objects.equals(this.paymentInfo, shippingOrder.paymentInfo) &&
        Objects.equals(this.requestedCarrier, shippingOrder.requestedCarrier) &&
        Objects.equals(this.requestedDeliveryDate, shippingOrder.requestedDeliveryDate) &&
        Objects.equals(this.shipAddrInfo, shippingOrder.shipAddrInfo) &&
        Objects.equals(this.shipFromAddrInfo, shippingOrder.shipFromAddrInfo) &&
        Objects.equals(this.shipmentDate, shippingOrder.shipmentDate) &&
        Objects.equals(this.shippingCharge, shippingOrder.shippingCharge) &&
        Objects.equals(this.shippingOrderLine, shippingOrder.shippingOrderLine) &&
        Objects.equals(this.shippingStatus, shippingOrder.shippingStatus) &&
        Objects.equals(this.storeToFulfillFrom, shippingOrder.storeToFulfillFrom) &&
        Objects.equals(this.type, shippingOrder.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actualCarrier, createdBy, fulfillmentMethod, fulfillmentPartner, globalContractId, id, isCustomerInvoiceAvailable, paymentInfo, requestedCarrier, requestedDeliveryDate, shipAddrInfo, shipFromAddrInfo, shipmentDate, shippingCharge, shippingOrderLine, shippingStatus, storeToFulfillFrom, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingOrder {\n");
    
    sb.append("    actualCarrier: ").append(toIndentedString(actualCarrier)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    fulfillmentMethod: ").append(toIndentedString(fulfillmentMethod)).append("\n");
    sb.append("    fulfillmentPartner: ").append(toIndentedString(fulfillmentPartner)).append("\n");
    sb.append("    globalContractId: ").append(toIndentedString(globalContractId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isCustomerInvoiceAvailable: ").append(toIndentedString(isCustomerInvoiceAvailable)).append("\n");
    sb.append("    paymentInfo: ").append(toIndentedString(paymentInfo)).append("\n");
    sb.append("    requestedCarrier: ").append(toIndentedString(requestedCarrier)).append("\n");
    sb.append("    requestedDeliveryDate: ").append(toIndentedString(requestedDeliveryDate)).append("\n");
    sb.append("    shipAddrInfo: ").append(toIndentedString(shipAddrInfo)).append("\n");
    sb.append("    shipFromAddrInfo: ").append(toIndentedString(shipFromAddrInfo)).append("\n");
    sb.append("    shipmentDate: ").append(toIndentedString(shipmentDate)).append("\n");
    sb.append("    shippingCharge: ").append(toIndentedString(shippingCharge)).append("\n");
    sb.append("    shippingOrderLine: ").append(toIndentedString(shippingOrderLine)).append("\n");
    sb.append("    shippingStatus: ").append(toIndentedString(shippingStatus)).append("\n");
    sb.append("    storeToFulfillFrom: ").append(toIndentedString(storeToFulfillFrom)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

