/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ShipFromAddrInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T17:40:22.226-08:00")
public class ShipFromAddrInfo {
  @JsonProperty("addr1")
  private String addr1 = null;

  @JsonProperty("addr2")
  private String addr2 = null;

  @JsonProperty("addr3")
  private String addr3 = null;

  @JsonProperty("aptNumber")
  private String aptNumber = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("faxNumber")
  private String faxNumber = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("otherPhone")
  private String otherPhone = null;

  @JsonProperty("otherPhoneExt")
  private String otherPhoneExt = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("phoneExt")
  private String phoneExt = null;

  @JsonProperty("postcode")
  private String postcode = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("uscounty")
  private String uscounty = null;

  public ShipFromAddrInfo addr1(String addr1) {
    this.addr1 = addr1;
    return this;
  }

   /**
   * Get addr1
   * @return addr1
  **/
  @ApiModelProperty(value = "")
  public String getAddr1() {
    return addr1;
  }

  public void setAddr1(String addr1) {
    this.addr1 = addr1;
  }

  public ShipFromAddrInfo addr2(String addr2) {
    this.addr2 = addr2;
    return this;
  }

   /**
   * Get addr2
   * @return addr2
  **/
  @ApiModelProperty(value = "")
  public String getAddr2() {
    return addr2;
  }

  public void setAddr2(String addr2) {
    this.addr2 = addr2;
  }

  public ShipFromAddrInfo addr3(String addr3) {
    this.addr3 = addr3;
    return this;
  }

   /**
   * Get addr3
   * @return addr3
  **/
  @ApiModelProperty(value = "")
  public String getAddr3() {
    return addr3;
  }

  public void setAddr3(String addr3) {
    this.addr3 = addr3;
  }

  public ShipFromAddrInfo aptNumber(String aptNumber) {
    this.aptNumber = aptNumber;
    return this;
  }

   /**
   * Get aptNumber
   * @return aptNumber
  **/
  @ApiModelProperty(value = "")
  public String getAptNumber() {
    return aptNumber;
  }

  public void setAptNumber(String aptNumber) {
    this.aptNumber = aptNumber;
  }

  public ShipFromAddrInfo city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ShipFromAddrInfo country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public ShipFromAddrInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ShipFromAddrInfo faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Get faxNumber
   * @return faxNumber
  **/
  @ApiModelProperty(value = "")
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public ShipFromAddrInfo firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ShipFromAddrInfo lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ShipFromAddrInfo locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public ShipFromAddrInfo otherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
    return this;
  }

   /**
   * Get otherPhone
   * @return otherPhone
  **/
  @ApiModelProperty(value = "")
  public String getOtherPhone() {
    return otherPhone;
  }

  public void setOtherPhone(String otherPhone) {
    this.otherPhone = otherPhone;
  }

  public ShipFromAddrInfo otherPhoneExt(String otherPhoneExt) {
    this.otherPhoneExt = otherPhoneExt;
    return this;
  }

   /**
   * Get otherPhoneExt
   * @return otherPhoneExt
  **/
  @ApiModelProperty(value = "")
  public String getOtherPhoneExt() {
    return otherPhoneExt;
  }

  public void setOtherPhoneExt(String otherPhoneExt) {
    this.otherPhoneExt = otherPhoneExt;
  }

  public ShipFromAddrInfo phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public ShipFromAddrInfo phoneExt(String phoneExt) {
    this.phoneExt = phoneExt;
    return this;
  }

   /**
   * Get phoneExt
   * @return phoneExt
  **/
  @ApiModelProperty(value = "")
  public String getPhoneExt() {
    return phoneExt;
  }

  public void setPhoneExt(String phoneExt) {
    this.phoneExt = phoneExt;
  }

  public ShipFromAddrInfo postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @ApiModelProperty(value = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public ShipFromAddrInfo province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  @ApiModelProperty(value = "")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public ShipFromAddrInfo uscounty(String uscounty) {
    this.uscounty = uscounty;
    return this;
  }

   /**
   * Get uscounty
   * @return uscounty
  **/
  @ApiModelProperty(value = "")
  public String getUscounty() {
    return uscounty;
  }

  public void setUscounty(String uscounty) {
    this.uscounty = uscounty;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipFromAddrInfo shipFromAddrInfo = (ShipFromAddrInfo) o;
    return Objects.equals(this.addr1, shipFromAddrInfo.addr1) &&
        Objects.equals(this.addr2, shipFromAddrInfo.addr2) &&
        Objects.equals(this.addr3, shipFromAddrInfo.addr3) &&
        Objects.equals(this.aptNumber, shipFromAddrInfo.aptNumber) &&
        Objects.equals(this.city, shipFromAddrInfo.city) &&
        Objects.equals(this.country, shipFromAddrInfo.country) &&
        Objects.equals(this.email, shipFromAddrInfo.email) &&
        Objects.equals(this.faxNumber, shipFromAddrInfo.faxNumber) &&
        Objects.equals(this.firstName, shipFromAddrInfo.firstName) &&
        Objects.equals(this.lastName, shipFromAddrInfo.lastName) &&
        Objects.equals(this.locationId, shipFromAddrInfo.locationId) &&
        Objects.equals(this.otherPhone, shipFromAddrInfo.otherPhone) &&
        Objects.equals(this.otherPhoneExt, shipFromAddrInfo.otherPhoneExt) &&
        Objects.equals(this.phone, shipFromAddrInfo.phone) &&
        Objects.equals(this.phoneExt, shipFromAddrInfo.phoneExt) &&
        Objects.equals(this.postcode, shipFromAddrInfo.postcode) &&
        Objects.equals(this.province, shipFromAddrInfo.province) &&
        Objects.equals(this.uscounty, shipFromAddrInfo.uscounty);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addr1, addr2, addr3, aptNumber, city, country, email, faxNumber, firstName, lastName, locationId, otherPhone, otherPhoneExt, phone, phoneExt, postcode, province, uscounty);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipFromAddrInfo {\n");
    
    sb.append("    addr1: ").append(toIndentedString(addr1)).append("\n");
    sb.append("    addr2: ").append(toIndentedString(addr2)).append("\n");
    sb.append("    addr3: ").append(toIndentedString(addr3)).append("\n");
    sb.append("    aptNumber: ").append(toIndentedString(aptNumber)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    otherPhone: ").append(toIndentedString(otherPhone)).append("\n");
    sb.append("    otherPhoneExt: ").append(toIndentedString(otherPhoneExt)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    phoneExt: ").append(toIndentedString(phoneExt)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    uscounty: ").append(toIndentedString(uscounty)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

