/*
 * Order Details Service REST API
 * REST API for rertrieving details of various order types.
 *
 * OpenAPI spec version: 1
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetailsservice;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * XMLGregorianCalendar
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-08T10:16:57.900-08:00")
public class XMLGregorianCalendar {
  @JsonProperty("day")
  private Integer day = null;

  @JsonProperty("eon")
  private Integer eon = null;

  @JsonProperty("eonAndYear")
  private Integer eonAndYear = null;

  @JsonProperty("fractionalSecond")
  private BigDecimal fractionalSecond = null;

  @JsonProperty("hour")
  private Integer hour = null;

  @JsonProperty("millisecond")
  private Integer millisecond = null;

  @JsonProperty("minute")
  private Integer minute = null;

  @JsonProperty("month")
  private Integer month = null;

  @JsonProperty("second")
  private Integer second = null;

  @JsonProperty("timezone")
  private Integer timezone = null;

  @JsonProperty("valid")
  private Boolean valid = null;

  @JsonProperty("xmlschemaType")
  private QName xmlschemaType = null;

  @JsonProperty("year")
  private Integer year = null;

  public XMLGregorianCalendar day(Integer day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(value = "")
  public Integer getDay() {
    return day;
  }

  public void setDay(Integer day) {
    this.day = day;
  }

  public XMLGregorianCalendar eon(Integer eon) {
    this.eon = eon;
    return this;
  }

   /**
   * Get eon
   * @return eon
  **/
  @ApiModelProperty(value = "")
  public Integer getEon() {
    return eon;
  }

  public void setEon(Integer eon) {
    this.eon = eon;
  }

  public XMLGregorianCalendar eonAndYear(Integer eonAndYear) {
    this.eonAndYear = eonAndYear;
    return this;
  }

   /**
   * Get eonAndYear
   * @return eonAndYear
  **/
  @ApiModelProperty(value = "")
  public Integer getEonAndYear() {
    return eonAndYear;
  }

  public void setEonAndYear(Integer eonAndYear) {
    this.eonAndYear = eonAndYear;
  }

  public XMLGregorianCalendar fractionalSecond(BigDecimal fractionalSecond) {
    this.fractionalSecond = fractionalSecond;
    return this;
  }

   /**
   * Get fractionalSecond
   * @return fractionalSecond
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getFractionalSecond() {
    return fractionalSecond;
  }

  public void setFractionalSecond(BigDecimal fractionalSecond) {
    this.fractionalSecond = fractionalSecond;
  }

  public XMLGregorianCalendar hour(Integer hour) {
    this.hour = hour;
    return this;
  }

   /**
   * Get hour
   * @return hour
  **/
  @ApiModelProperty(value = "")
  public Integer getHour() {
    return hour;
  }

  public void setHour(Integer hour) {
    this.hour = hour;
  }

  public XMLGregorianCalendar millisecond(Integer millisecond) {
    this.millisecond = millisecond;
    return this;
  }

   /**
   * Get millisecond
   * @return millisecond
  **/
  @ApiModelProperty(value = "")
  public Integer getMillisecond() {
    return millisecond;
  }

  public void setMillisecond(Integer millisecond) {
    this.millisecond = millisecond;
  }

  public XMLGregorianCalendar minute(Integer minute) {
    this.minute = minute;
    return this;
  }

   /**
   * Get minute
   * @return minute
  **/
  @ApiModelProperty(value = "")
  public Integer getMinute() {
    return minute;
  }

  public void setMinute(Integer minute) {
    this.minute = minute;
  }

  public XMLGregorianCalendar month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @ApiModelProperty(value = "")
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public XMLGregorianCalendar second(Integer second) {
    this.second = second;
    return this;
  }

   /**
   * Get second
   * @return second
  **/
  @ApiModelProperty(value = "")
  public Integer getSecond() {
    return second;
  }

  public void setSecond(Integer second) {
    this.second = second;
  }

  public XMLGregorianCalendar timezone(Integer timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public Integer getTimezone() {
    return timezone;
  }

  public void setTimezone(Integer timezone) {
    this.timezone = timezone;
  }

  public XMLGregorianCalendar valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @ApiModelProperty(value = "")
  public Boolean getValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }

  public XMLGregorianCalendar xmlschemaType(QName xmlschemaType) {
    this.xmlschemaType = xmlschemaType;
    return this;
  }

   /**
   * Get xmlschemaType
   * @return xmlschemaType
  **/
  @ApiModelProperty(value = "")
  public QName getXmlschemaType() {
    return xmlschemaType;
  }

  public void setXmlschemaType(QName xmlschemaType) {
    this.xmlschemaType = xmlschemaType;
  }

  public XMLGregorianCalendar year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(value = "")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XMLGregorianCalendar xmLGregorianCalendar = (XMLGregorianCalendar) o;
    return Objects.equals(this.day, xmLGregorianCalendar.day) &&
        Objects.equals(this.eon, xmLGregorianCalendar.eon) &&
        Objects.equals(this.eonAndYear, xmLGregorianCalendar.eonAndYear) &&
        Objects.equals(this.fractionalSecond, xmLGregorianCalendar.fractionalSecond) &&
        Objects.equals(this.hour, xmLGregorianCalendar.hour) &&
        Objects.equals(this.millisecond, xmLGregorianCalendar.millisecond) &&
        Objects.equals(this.minute, xmLGregorianCalendar.minute) &&
        Objects.equals(this.month, xmLGregorianCalendar.month) &&
        Objects.equals(this.second, xmLGregorianCalendar.second) &&
        Objects.equals(this.timezone, xmLGregorianCalendar.timezone) &&
        Objects.equals(this.valid, xmLGregorianCalendar.valid) &&
        Objects.equals(this.xmlschemaType, xmLGregorianCalendar.xmlschemaType) &&
        Objects.equals(this.year, xmLGregorianCalendar.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, eon, eonAndYear, fractionalSecond, hour, millisecond, minute, month, second, timezone, valid, xmlschemaType, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XMLGregorianCalendar {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    eon: ").append(toIndentedString(eon)).append("\n");
    sb.append("    eonAndYear: ").append(toIndentedString(eonAndYear)).append("\n");
    sb.append("    fractionalSecond: ").append(toIndentedString(fractionalSecond)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    millisecond: ").append(toIndentedString(millisecond)).append("\n");
    sb.append("    minute: ").append(toIndentedString(minute)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    second: ").append(toIndentedString(second)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    xmlschemaType: ").append(toIndentedString(xmlschemaType)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

