/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetails;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetails.Address;
import com.bbyc.orders.model.client.orderdetails.Status;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CreditCardInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-13T17:36:04.633-08:00")
public class CreditCardInfo {
  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("avsStatus")
  private Status avsStatus = null;

  @JsonProperty("billingAddress")
  private Address billingAddress = null;

  @JsonProperty("creditCardNumber")
  private String creditCardNumber = null;

  @JsonProperty("creditCardType")
  private String creditCardType = null;

  @JsonProperty("creditCardExpiryDate")
  private String creditCardExpiryDate = null;

  @JsonProperty("creditCardHolderName")
  private String creditCardHolderName = null;

  @JsonProperty("invoicedAmount")
  private Float invoicedAmount = null;

  @JsonProperty("priority")
  private String priority = null;

  public CreditCardInfo active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public CreditCardInfo avsStatus(Status avsStatus) {
    this.avsStatus = avsStatus;
    return this;
  }

   /**
   * Get avsStatus
   * @return avsStatus
  **/
  @ApiModelProperty(value = "")
  public Status getAvsStatus() {
    return avsStatus;
  }

  public void setAvsStatus(Status avsStatus) {
    this.avsStatus = avsStatus;
  }

  public CreditCardInfo billingAddress(Address billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @ApiModelProperty(value = "")
  public Address getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(Address billingAddress) {
    this.billingAddress = billingAddress;
  }

  public CreditCardInfo creditCardNumber(String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
    return this;
  }

   /**
   * Get creditCardNumber
   * @return creditCardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCreditCardNumber() {
    return creditCardNumber;
  }

  public void setCreditCardNumber(String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
  }

  public CreditCardInfo creditCardType(String creditCardType) {
    this.creditCardType = creditCardType;
    return this;
  }

   /**
   * Get creditCardType
   * @return creditCardType
  **/
  @ApiModelProperty(value = "")
  public String getCreditCardType() {
    return creditCardType;
  }

  public void setCreditCardType(String creditCardType) {
    this.creditCardType = creditCardType;
  }

  public CreditCardInfo creditCardExpiryDate(String creditCardExpiryDate) {
    this.creditCardExpiryDate = creditCardExpiryDate;
    return this;
  }

   /**
   * Get creditCardExpiryDate
   * @return creditCardExpiryDate
  **/
  @ApiModelProperty(value = "")
  public String getCreditCardExpiryDate() {
    return creditCardExpiryDate;
  }

  public void setCreditCardExpiryDate(String creditCardExpiryDate) {
    this.creditCardExpiryDate = creditCardExpiryDate;
  }

  public CreditCardInfo creditCardHolderName(String creditCardHolderName) {
    this.creditCardHolderName = creditCardHolderName;
    return this;
  }

   /**
   * Get creditCardHolderName
   * @return creditCardHolderName
  **/
  @ApiModelProperty(value = "")
  public String getCreditCardHolderName() {
    return creditCardHolderName;
  }

  public void setCreditCardHolderName(String creditCardHolderName) {
    this.creditCardHolderName = creditCardHolderName;
  }

  public CreditCardInfo invoicedAmount(Float invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
    return this;
  }

   /**
   * Get invoicedAmount
   * @return invoicedAmount
  **/
  @ApiModelProperty(value = "")
  public Float getInvoicedAmount() {
    return invoicedAmount;
  }

  public void setInvoicedAmount(Float invoicedAmount) {
    this.invoicedAmount = invoicedAmount;
  }

  public CreditCardInfo priority(String priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public String getPriority() {
    return priority;
  }

  public void setPriority(String priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditCardInfo creditCardInfo = (CreditCardInfo) o;
    return Objects.equals(this.active, creditCardInfo.active) &&
        Objects.equals(this.avsStatus, creditCardInfo.avsStatus) &&
        Objects.equals(this.billingAddress, creditCardInfo.billingAddress) &&
        Objects.equals(this.creditCardNumber, creditCardInfo.creditCardNumber) &&
        Objects.equals(this.creditCardType, creditCardInfo.creditCardType) &&
        Objects.equals(this.creditCardExpiryDate, creditCardInfo.creditCardExpiryDate) &&
        Objects.equals(this.creditCardHolderName, creditCardInfo.creditCardHolderName) &&
        Objects.equals(this.invoicedAmount, creditCardInfo.invoicedAmount) &&
        Objects.equals(this.priority, creditCardInfo.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, avsStatus, billingAddress, creditCardNumber, creditCardType, creditCardExpiryDate, creditCardHolderName, invoicedAmount, priority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditCardInfo {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    avsStatus: ").append(toIndentedString(avsStatus)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    creditCardNumber: ").append(toIndentedString(creditCardNumber)).append("\n");
    sb.append("    creditCardType: ").append(toIndentedString(creditCardType)).append("\n");
    sb.append("    creditCardExpiryDate: ").append(toIndentedString(creditCardExpiryDate)).append("\n");
    sb.append("    creditCardHolderName: ").append(toIndentedString(creditCardHolderName)).append("\n");
    sb.append("    invoicedAmount: ").append(toIndentedString(invoicedAmount)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

