/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetails;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetails.EffectiveDateRange;
import com.bbyc.orders.model.client.orderdetails.Term;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ProductServicePlan
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-13T11:58:37.070-08:00")
public class ProductServicePlan {
  @JsonProperty("effectiveDateRange")
  private EffectiveDateRange effectiveDateRange = null;

  @JsonProperty("pspCoveredSerialNumbers")
  private List<String> pspCoveredSerialNumbers = null;

  @JsonProperty("term")
  private Term term = null;

  public ProductServicePlan effectiveDateRange(EffectiveDateRange effectiveDateRange) {
    this.effectiveDateRange = effectiveDateRange;
    return this;
  }

   /**
   * Get effectiveDateRange
   * @return effectiveDateRange
  **/
  @ApiModelProperty(value = "")
  public EffectiveDateRange getEffectiveDateRange() {
    return effectiveDateRange;
  }

  public void setEffectiveDateRange(EffectiveDateRange effectiveDateRange) {
    this.effectiveDateRange = effectiveDateRange;
  }

  public ProductServicePlan pspCoveredSerialNumbers(List<String> pspCoveredSerialNumbers) {
    this.pspCoveredSerialNumbers = pspCoveredSerialNumbers;
    return this;
  }

  public ProductServicePlan addPspCoveredSerialNumbersItem(String pspCoveredSerialNumbersItem) {
    if (this.pspCoveredSerialNumbers == null) {
      this.pspCoveredSerialNumbers = new ArrayList<String>();
    }
    this.pspCoveredSerialNumbers.add(pspCoveredSerialNumbersItem);
    return this;
  }

   /**
   * Get pspCoveredSerialNumbers
   * @return pspCoveredSerialNumbers
  **/
  @ApiModelProperty(value = "")
  public List<String> getPspCoveredSerialNumbers() {
    return pspCoveredSerialNumbers;
  }

  public void setPspCoveredSerialNumbers(List<String> pspCoveredSerialNumbers) {
    this.pspCoveredSerialNumbers = pspCoveredSerialNumbers;
  }

  public ProductServicePlan term(Term term) {
    this.term = term;
    return this;
  }

   /**
   * Get term
   * @return term
  **/
  @ApiModelProperty(value = "")
  public Term getTerm() {
    return term;
  }

  public void setTerm(Term term) {
    this.term = term;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductServicePlan productServicePlan = (ProductServicePlan) o;
    return Objects.equals(this.effectiveDateRange, productServicePlan.effectiveDateRange) &&
        Objects.equals(this.pspCoveredSerialNumbers, productServicePlan.pspCoveredSerialNumbers) &&
        Objects.equals(this.term, productServicePlan.term);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveDateRange, pspCoveredSerialNumbers, term);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductServicePlan {\n");
    
    sb.append("    effectiveDateRange: ").append(toIndentedString(effectiveDateRange)).append("\n");
    sb.append("    pspCoveredSerialNumbers: ").append(toIndentedString(pspCoveredSerialNumbers)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

