/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetails;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetails.FulfillmentLocationIdentifier;
import com.bbyc.orders.model.client.orderdetails.FulfillmentPartnerProduct;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;

/**
 * PurchaseOrderLine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-13T11:58:37.070-08:00")
public class PurchaseOrderLine {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("availability")
  private String availability = null;

  @JsonProperty("deliveryDate")
  private LocalDate deliveryDate = null;

  @JsonProperty("etaDate")
  private LocalDate etaDate = null;

  @JsonProperty("fulfillmentPartnerPOLineRefId")
  private String fulfillmentPartnerPOLineRefId = null;

  @JsonProperty("fulfillmentPartnerProduct")
  private FulfillmentPartnerProduct fulfillmentPartnerProduct = null;

  @JsonProperty("fulfillmentLocationIdentifier")
  private FulfillmentLocationIdentifier fulfillmentLocationIdentifier = null;

  @JsonProperty("fsoLineRefId")
  private String fsoLineRefId = null;

  @JsonProperty("qtyAllocated")
  private String qtyAllocated = null;

  @JsonProperty("qtyBackordered")
  private String qtyBackordered = null;

  @JsonProperty("qtyOrdered")
  private String qtyOrdered = null;

  @JsonProperty("releaseDate")
  private OffsetDateTime releaseDate = null;

  @JsonProperty("shippingOrderLineRefId")
  private String shippingOrderLineRefId = null;

  public PurchaseOrderLine id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PurchaseOrderLine availability(String availability) {
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @ApiModelProperty(value = "")
  public String getAvailability() {
    return availability;
  }

  public void setAvailability(String availability) {
    this.availability = availability;
  }

  public PurchaseOrderLine deliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
    return this;
  }

   /**
   * Get deliveryDate
   * @return deliveryDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDeliveryDate() {
    return deliveryDate;
  }

  public void setDeliveryDate(LocalDate deliveryDate) {
    this.deliveryDate = deliveryDate;
  }

  public PurchaseOrderLine etaDate(LocalDate etaDate) {
    this.etaDate = etaDate;
    return this;
  }

   /**
   * Get etaDate
   * @return etaDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getEtaDate() {
    return etaDate;
  }

  public void setEtaDate(LocalDate etaDate) {
    this.etaDate = etaDate;
  }

  public PurchaseOrderLine fulfillmentPartnerPOLineRefId(String fulfillmentPartnerPOLineRefId) {
    this.fulfillmentPartnerPOLineRefId = fulfillmentPartnerPOLineRefId;
    return this;
  }

   /**
   * Get fulfillmentPartnerPOLineRefId
   * @return fulfillmentPartnerPOLineRefId
  **/
  @ApiModelProperty(value = "")
  public String getFulfillmentPartnerPOLineRefId() {
    return fulfillmentPartnerPOLineRefId;
  }

  public void setFulfillmentPartnerPOLineRefId(String fulfillmentPartnerPOLineRefId) {
    this.fulfillmentPartnerPOLineRefId = fulfillmentPartnerPOLineRefId;
  }

  public PurchaseOrderLine fulfillmentPartnerProduct(FulfillmentPartnerProduct fulfillmentPartnerProduct) {
    this.fulfillmentPartnerProduct = fulfillmentPartnerProduct;
    return this;
  }

   /**
   * Get fulfillmentPartnerProduct
   * @return fulfillmentPartnerProduct
  **/
  @ApiModelProperty(value = "")
  public FulfillmentPartnerProduct getFulfillmentPartnerProduct() {
    return fulfillmentPartnerProduct;
  }

  public void setFulfillmentPartnerProduct(FulfillmentPartnerProduct fulfillmentPartnerProduct) {
    this.fulfillmentPartnerProduct = fulfillmentPartnerProduct;
  }

  public PurchaseOrderLine fulfillmentLocationIdentifier(FulfillmentLocationIdentifier fulfillmentLocationIdentifier) {
    this.fulfillmentLocationIdentifier = fulfillmentLocationIdentifier;
    return this;
  }

   /**
   * Get fulfillmentLocationIdentifier
   * @return fulfillmentLocationIdentifier
  **/
  @ApiModelProperty(value = "")
  public FulfillmentLocationIdentifier getFulfillmentLocationIdentifier() {
    return fulfillmentLocationIdentifier;
  }

  public void setFulfillmentLocationIdentifier(FulfillmentLocationIdentifier fulfillmentLocationIdentifier) {
    this.fulfillmentLocationIdentifier = fulfillmentLocationIdentifier;
  }

  public PurchaseOrderLine fsoLineRefId(String fsoLineRefId) {
    this.fsoLineRefId = fsoLineRefId;
    return this;
  }

   /**
   * Get fsoLineRefId
   * @return fsoLineRefId
  **/
  @ApiModelProperty(value = "")
  public String getFsoLineRefId() {
    return fsoLineRefId;
  }

  public void setFsoLineRefId(String fsoLineRefId) {
    this.fsoLineRefId = fsoLineRefId;
  }

  public PurchaseOrderLine qtyAllocated(String qtyAllocated) {
    this.qtyAllocated = qtyAllocated;
    return this;
  }

   /**
   * Get qtyAllocated
   * @return qtyAllocated
  **/
  @ApiModelProperty(value = "")
  public String getQtyAllocated() {
    return qtyAllocated;
  }

  public void setQtyAllocated(String qtyAllocated) {
    this.qtyAllocated = qtyAllocated;
  }

  public PurchaseOrderLine qtyBackordered(String qtyBackordered) {
    this.qtyBackordered = qtyBackordered;
    return this;
  }

   /**
   * Get qtyBackordered
   * @return qtyBackordered
  **/
  @ApiModelProperty(value = "")
  public String getQtyBackordered() {
    return qtyBackordered;
  }

  public void setQtyBackordered(String qtyBackordered) {
    this.qtyBackordered = qtyBackordered;
  }

  public PurchaseOrderLine qtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
    return this;
  }

   /**
   * Get qtyOrdered
   * @return qtyOrdered
  **/
  @ApiModelProperty(value = "")
  public String getQtyOrdered() {
    return qtyOrdered;
  }

  public void setQtyOrdered(String qtyOrdered) {
    this.qtyOrdered = qtyOrdered;
  }

  public PurchaseOrderLine releaseDate(OffsetDateTime releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(OffsetDateTime releaseDate) {
    this.releaseDate = releaseDate;
  }

  public PurchaseOrderLine shippingOrderLineRefId(String shippingOrderLineRefId) {
    this.shippingOrderLineRefId = shippingOrderLineRefId;
    return this;
  }

   /**
   * Get shippingOrderLineRefId
   * @return shippingOrderLineRefId
  **/
  @ApiModelProperty(value = "")
  public String getShippingOrderLineRefId() {
    return shippingOrderLineRefId;
  }

  public void setShippingOrderLineRefId(String shippingOrderLineRefId) {
    this.shippingOrderLineRefId = shippingOrderLineRefId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrderLine purchaseOrderLine = (PurchaseOrderLine) o;
    return Objects.equals(this.id, purchaseOrderLine.id) &&
        Objects.equals(this.availability, purchaseOrderLine.availability) &&
        Objects.equals(this.deliveryDate, purchaseOrderLine.deliveryDate) &&
        Objects.equals(this.etaDate, purchaseOrderLine.etaDate) &&
        Objects.equals(this.fulfillmentPartnerPOLineRefId, purchaseOrderLine.fulfillmentPartnerPOLineRefId) &&
        Objects.equals(this.fulfillmentPartnerProduct, purchaseOrderLine.fulfillmentPartnerProduct) &&
        Objects.equals(this.fulfillmentLocationIdentifier, purchaseOrderLine.fulfillmentLocationIdentifier) &&
        Objects.equals(this.fsoLineRefId, purchaseOrderLine.fsoLineRefId) &&
        Objects.equals(this.qtyAllocated, purchaseOrderLine.qtyAllocated) &&
        Objects.equals(this.qtyBackordered, purchaseOrderLine.qtyBackordered) &&
        Objects.equals(this.qtyOrdered, purchaseOrderLine.qtyOrdered) &&
        Objects.equals(this.releaseDate, purchaseOrderLine.releaseDate) &&
        Objects.equals(this.shippingOrderLineRefId, purchaseOrderLine.shippingOrderLineRefId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, availability, deliveryDate, etaDate, fulfillmentPartnerPOLineRefId, fulfillmentPartnerProduct, fulfillmentLocationIdentifier, fsoLineRefId, qtyAllocated, qtyBackordered, qtyOrdered, releaseDate, shippingOrderLineRefId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrderLine {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
    sb.append("    etaDate: ").append(toIndentedString(etaDate)).append("\n");
    sb.append("    fulfillmentPartnerPOLineRefId: ").append(toIndentedString(fulfillmentPartnerPOLineRefId)).append("\n");
    sb.append("    fulfillmentPartnerProduct: ").append(toIndentedString(fulfillmentPartnerProduct)).append("\n");
    sb.append("    fulfillmentLocationIdentifier: ").append(toIndentedString(fulfillmentLocationIdentifier)).append("\n");
    sb.append("    fsoLineRefId: ").append(toIndentedString(fsoLineRefId)).append("\n");
    sb.append("    qtyAllocated: ").append(toIndentedString(qtyAllocated)).append("\n");
    sb.append("    qtyBackordered: ").append(toIndentedString(qtyBackordered)).append("\n");
    sb.append("    qtyOrdered: ").append(toIndentedString(qtyOrdered)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    shippingOrderLineRefId: ").append(toIndentedString(shippingOrderLineRefId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

