/*
 * Order Details Service REST API
 * REST API for retrieving details of an order.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: eCommCAOrders@bestbuy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bbyc.orders.model.client.orderdetails;

import java.util.Objects;
import com.bbyc.orders.model.client.orderdetails.LevelOfService;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RequestedCarrier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-14T15:03:30.736-08:00")
public class RequestedCarrier {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("levelOfService")
  private LevelOfService levelOfService = null;

  @JsonProperty("name")
  private String name = null;

  public RequestedCarrier id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RequestedCarrier levelOfService(LevelOfService levelOfService) {
    this.levelOfService = levelOfService;
    return this;
  }

   /**
   * Get levelOfService
   * @return levelOfService
  **/
  @ApiModelProperty(value = "")
  public LevelOfService getLevelOfService() {
    return levelOfService;
  }

  public void setLevelOfService(LevelOfService levelOfService) {
    this.levelOfService = levelOfService;
  }

  public RequestedCarrier name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestedCarrier requestedCarrier = (RequestedCarrier) o;
    return Objects.equals(this.id, requestedCarrier.id) &&
        Objects.equals(this.levelOfService, requestedCarrier.levelOfService) &&
        Objects.equals(this.name, requestedCarrier.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, levelOfService, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestedCarrier {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    levelOfService: ").append(toIndentedString(levelOfService)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

