apiVersion: v1
kind: DeploymentConfig
metadata:
  name: bby-orders-fraud-service
  labels:
    app: bby-orders-fraud-service
    name: bby-orders-fraud-service
spec:
  replicas: 1
  selector:
    app: bby-orders-fraud-service
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 100%
      maxUnavailable: 100%
      timeoutSeconds: 60
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/container.config-service.image.entrypoint: '["container-entrypoint","/bin/sh","-c","$STI_SCRIPTS_PATH/usage"]'
      labels:
        app: bby-orders-fraud-service
        name: bby-orders-fraud-service
    spec:
      containers:
      - image: bby-orders-fraud-service:latest
        imagePullPolicy: Always
        name: bby-orders-fraud-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers: []
status: {}