def appName="bby-orders-fraud-service"
def project="ecomm-orders-team"

node('maven') {

    stage('Checkout Source Code') {
        checkout scm
    }

    stage('Build') {
        sh "mvn clean compile"
    }

//    stage('Execute Tests') {
//        sh "mvn test"
//    }

    stage('Package') {
        sh "mvn package -DskipTests=true"
        sh "mv target/*.jar ${appName}.jar"
    }

    stage('Create Container Image') {

        sh "oc start-build ${appName} --from-file=${appName}.jar --follow -n ${project}"

    }
}