apiVersion: v1
kind: BuildConfig
metadata:
  name: bby-orders-fraud-service-pipeline
  namespace: ecomm-orders-team
  labels:
    app: bby-orders-fraud-service-pipeline
spec:
  triggers: []
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "ssh://git@bitbucketdev.ca.bestbuy.com:7999/or/order-fraud-service.git"
      ref: openshift-deployment
    sourceSecret:
      name: openshift-source-builder-orders
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift-config/Jenkinsfile
  output: {}
  resources: {}
  postCommit: {}
  nodeSelector: null