INSERT INTO ORDER_FRAUD.ID_GENERATOR (GENERATED_NAME, GENERATED_VALUE) VALUES ('FRAUDREQUESTID', 0);
INSERT INTO ORDER_FRAUD.ID_GENERATOR (GENERATED_NAME, GENERATED_VALUE) VALUES ('FRAUDREQUESTSTATUSHISTORYID', 0);

INSERT INTO ORDER_FRAUD.FRAUDSTATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('INITIAL_REQUEST', 'Initial request received.', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUDSTATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('DECISION_MADE', 'Final fraud decision is made.', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUDSTATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('PENDING_REVIEW', 'Fraud decision is pending manual review.', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUDSTATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('CANCELLED', 'Fraud assessment is canceled.', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');


INSERT INTO ORDER_FRAUD.FRAUDREQUESTTYPES (REQUESTTYPECODE, REQUESTTYPEDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('FRAUD_CHECK', 'Fraud check request', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUDREQUESTTYPES (REQUESTTYPECODE, REQUESTTYPEDESCRIPTION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('ORDER_CANCEL', 'Order cancellation', SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');
