INSERT INTO ORDER_FRAUD.ID_GENERATOR (GENERATED_NAME, GENERATED_VALUE) VALUES ('FRAUDREQUESTID', 0);
INSERT INTO ORDER_FRAUD.ID_GENERATOR (GENERATED_NAME, GENERATED_VALUE) VALUES ('FRAUDREQUESTSTATUSHISTORYID', 0);

INSERT INTO ORDER_FRAUD.FRAUD_STATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, VERSION, CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('INITIAL_REQUEST', 'Initial request received.', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUD_STATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, VERSION,CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('DECISION_MADE', 'Final fraud decision is made.', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUD_STATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, VERSION,CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('PENDING_REVIEW', 'Fraud decision is pending manual review.', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUD_STATUSES (FRAUDSTATUSCODE, FRAUDSTATUSDESCRIPTION, VERSION,CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('CANCELLED', 'Fraud assessment is canceled.', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');


INSERT INTO ORDER_FRAUD.FRAUD_RQST_TYPES (REQUESTTYPECODE, REQUESTTYPEDESCRIPTION, VERSION,CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('FRAUD_CHECK', 'Fraud check request', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');

INSERT INTO ORDER_FRAUD.FRAUD_RQST_TYPES (REQUESTTYPECODE, REQUESTTYPEDESCRIPTION, VERSION,CREATEDATE, CREATEUSER, UPDATEDATE, UPDATEUSER) 
VALUES ('ORDER_CANCEL', 'Order cancellation', 1, SYSDATE, 'ORDER_FRAUD_SCRIPT', SYSDATE, 'ORDER_FRAUD_SCRIPT');
