DROP SCHEMA ORDER_FRAUD IF EXISTS;
CREATE SCHEMA ORDER_FRAUD;

DROP TABLE ORDER_FRAUD.ID_GENERATOR IF EXISTS;
CREATE TABLE ORDER_FRAUD.ID_GENERATOR (
	GENERATED_NAME VARCHAR(80) NOT NULL,
	GENERATED_VALUE NUMBER NOT NULL
);
ALTER TABLE ORDER_FRAUD.ID_GENERATOR ADD CONSTRAINT ID_GENERATOR_PK PRIMARY KEY ( GENERATED_NAME );

DROP TABLE ORDER_FRAUD.FRAUD_RQST IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST (
    FRAUDREQUESTID    NUMBER NOT NULL,
--  fs order number
    ORDERNUMBER       NUMBER NOT NULL,
    EVENTDATE         DATE NOT NULL,
--  every time oms moves the fso to fraud check required,we will create a new version
    REQUESTVERSION    INTEGER NOT NULL,
    REQUESTTYPECODE   VARCHAR2(80 CHAR) NOT NULL,
    FRAUDSTATUSCODE   VARCHAR2(80 CHAR) NOT NULL,
	VERSION    		  INTEGER NOT NULL,
    CREATEDATE        DATE NOT NULL,
    CREATEUSER        VARCHAR2(80 CHAR) NOT NULL,
    UPDATEDATE        DATE NOT NULL,
    UPDATEUSER        VARCHAR2(80 CHAR) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST ADD CONSTRAINT FRAUD_RQST_PK PRIMARY KEY ( FRAUDREQUESTID );
ALTER TABLE ORDER_FRAUD.FRAUD_RQST ADD CONSTRAINT FRAUD_RQST_UN UNIQUE ( ORDERNUMBER, REQUESTVERSION );

DROP TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY (
    FRAUDREQUESTSTATUSHISTORYID   NUMBER NOT NULL,
    FRAUDREQUESTID          NUMBER NOT NULL,
    FRAUDSTATUSCODE         VARCHAR2(80 CHAR) NOT NULL,
	VERSION    		  		INTEGER NOT NULL,
    CREATEDATE             	DATE NOT NULL,
    CREATEUSER              VARCHAR2(80 CHAR) NOT NULL,
    UPDATEDATE              DATE NOT NULL,
    UPDATEUSER              VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY ADD CONSTRAINT FRAUD_RQST_STATUS_HSTRY_PK PRIMARY KEY ( FRAUDREQUESTSTATUSHISTORYID );

DROP TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS (
    FRAUDREQUESTSTATUSHISTORYID   NUMBER NOT NULL,
    TASREQUEST              CLOB NOT NULL,
    TASRESPONSE             CLOB NOT NULL,
	VERSION    		  		INTEGER NOT NULL,
    CREATEDATE              DATE NOT NULL,
    CREATEUSER              VARCHAR2(80) NOT NULL,
    UPDATEDATE              DATE NOT NULL,
    UPDATEUSER              VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS ADD CONSTRAINT FRD_RQST_STATUS_HSTRY_DTLS_PK PRIMARY KEY ( FRAUDREQUESTSTATUSHISTORYID );

DROP TABLE ORDER_FRAUD.FRAUD_STATUSES IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_STATUSES (
    FRAUDSTATUSCODE          VARCHAR2(80) NOT NULL,
    FRAUDSTATUSDESCRIPTION   VARCHAR2(2000 CHAR),
	VERSION    		  		 INTEGER NOT NULL,
    CREATEDATE               DATE NOT NULL,
    CREATEUSER               VARCHAR2(80) NOT NULL,
    UPDATEDATE               DATE NOT NULL,
    UPDATEUSER               VARCHAR2(80) NOT NULL
);
ALTER TABLE ORDER_FRAUD.FRAUD_STATUSES ADD CONSTRAINT FRAUD_STATUSES_PK PRIMARY KEY ( FRAUDSTATUSCODE );

DROP TABLE ORDER_FRAUD.FRAUD_RQST_TYPES IF EXISTS;
CREATE TABLE ORDER_FRAUD.FRAUD_RQST_TYPES (
    REQUESTTYPECODE          VARCHAR2(80 CHAR) NOT NULL,
    REQUESTTYPEDESCRIPTION   VARCHAR2(2000),
	VERSION    		  		 INTEGER NOT NULL,
    CREATEDATE               DATE NOT NULL,
    CREATEUSER               VARCHAR2(80) NOT NULL,
    UPDATEDATE               DATE NOT NULL,
    UPDATEUSER               VARCHAR2(80 CHAR) NOT NULL
); 
ALTER TABLE ORDER_FRAUD.FRAUD_RQST_TYPES ADD CONSTRAINT FRAUD_RQST_TYPES_PK PRIMARY KEY ( REQUESTTYPECODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST
    ADD CONSTRAINT FRDRQST_FRDSTATUSES_FK FOREIGN KEY ( FRAUDSTATUSCODE )
        REFERENCES ORDER_FRAUD.FRAUD_STATUSES ( FRAUDSTATUSCODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST
    ADD CONSTRAINT FRDRQST_RQST_TYPS_FK FOREIGN KEY ( REQUESTTYPECODE )
        REFERENCES ORDER_FRAUD.FRAUD_RQST_TYPES ( REQUESTTYPECODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY 
    ADD CONSTRAINT FRDRQSTHSTRY_FRDRQST_FK FOREIGN KEY ( FRAUDREQUESTID ) 
        REFERENCES ORDER_FRAUD.FRAUD_RQST ( FRAUDREQUESTID );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY
    ADD CONSTRAINT FRDRQSTHSTRY_FRDSTATUSES_FK FOREIGN KEY ( FRAUDSTATUSCODE )
        REFERENCES ORDER_FRAUD.FRAUD_STATUSES ( FRAUDSTATUSCODE );

ALTER TABLE ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY_DTLS
    ADD CONSTRAINT FRDRQSTHSTRYDTL_FRDRQSTHTRY_FK FOREIGN KEY ( FRAUDREQUESTSTATUSHISTORYID )
        REFERENCES ORDER_FRAUD.FRAUD_RQST_STATUS_HSTRY ( FRAUDREQUESTSTATUSHISTORYID );