CREATE TABLE FRAUDREQUEST (
    FRAUDREQUESTID    NUMBER NOT NULL,
--  fs order number
    ORDERNUMBER       NUMBER NOT NULL,
--  every time oms moves the fso to fraud check required,we will create a new version
    REQUESTVERSION    INTEGER NOT NULL,
    REQUESTTYPECODE   VARCHAR2(80 CHAR),
    FRAUDSTATUSCODE   VARCHAR2(80 CHAR),
    CREATEDATE        DATE NOT NULL,
    CREATEUSER        VARCHAR2(80 CHAR) NOT NULL,
    UPDATEDATE        DATE NOT NULL,
    UPDATEUSER        VARCHAR2(80 CHAR) NOT NULL
);

ALTER TABLE FRAUDREQUEST ADD CONSTRAINT FRAUDREQUEST_PK PRIMARY KEY ( FRAUDREQUESTID );
ALTER TABLE FRAUDREQUEST ADD CONSTRAINT FRAUDREQUEST_UN UNIQUE ( ORDERNUMBER );

CREATE TABLE FRAUDREQUESTHISTORY (
    FRAUDREQUESTHISTORYID   NUMBER NOT NULL,
    FRAUDREQUESTID          NUMBER NOT NULL,
    REQUESTTYPECODE         VARCHAR2(80) NOT NULL,
    ORDERNUMBER             NUMBER,
    REQUESTVERSION          INTEGER,
    FRAUDSTATUSCODE         VARCHAR2(80 CHAR),
    CREATENDATE             DATE,
    CREATEUSER              VARCHAR2(80),
    UPDATEDATE              DATE NOT NULL,
    UPDATEUSER              VARCHAR2(80) NOT NULL
);

ALTER TABLE FRAUDREQUESTHISTORY ADD CONSTRAINT FRAUDREQUESTHISTORY_PK PRIMARY KEY ( FRAUDREQUESTHISTORYID );

CREATE TABLE FRAUDREQUESTHISTORYDETAILS (
    FRAUDREQUESTHISTORYDETAILSID   NUMBER NOT NULL,
    FRAUDREQUESTHISTORYID   NUMBER NOT NULL,
    TASREQUEST              CLOB NOT NULL,
    TASRESPONSE             CLOB,
    CREATEDATE              DATE NOT NULL,
    CREATEUSER              VARCHAR2(80) NOT NULL,
    UPDATEDATE              DATE NOT NULL,
    UPDATEUSER              VARCHAR2(80) NOT NULL
);

ALTER TABLE FRAUDREQUESTHISTORYDETAILS ADD CONSTRAINT FRAUDREQUESTHISTORYDETAILS_PK PRIMARY KEY ( FRAUDREQUESTHISTORYDETAILSID );

CREATE TABLE FRAUDSTATUSES (
    FRAUDSTATUSCODE          VARCHAR2(80) NOT NULL,
    FRAUDSTATUSDESCRIPTION   VARCHAR2(2000 CHAR),
    CREATEDATE               DATE,
    CREATEUSER               VARCHAR2(80),
    UPDATEDATE               DATE,
    UPDATEUSER               VARCHAR2(80)
);

ALTER TABLE FRAUDSTATUSES ADD CONSTRAINT FRAUDSTATUSES_PK PRIMARY KEY ( FRAUDSTATUSCODE );

CREATE TABLE FRAUDREQUESTTYPES (
    REQUESTTYPECODE          VARCHAR2(80 CHAR) NOT NULL,
    REQUESTTYPEDESCRIPTION   VARCHAR2(2000),
    CREATEDATE               DATE,
    CREATEUSER               VARCHAR2(80),
    UPDATEDATE               DATE,
    UPDATEUSER               VARCHAR2(80 CHAR)
);

ALTER TABLE FRAUDREQUESTTYPES ADD CONSTRAINT FRAUDREQUESTTYPES_PK PRIMARY KEY ( REQUESTTYPECODE );

ALTER TABLE FRAUDREQUEST
    ADD CONSTRAINT FRDRQST_FRDSTATUSES_FK FOREIGN KEY ( FRAUDSTATUSCODE )
        REFERENCES FRAUDSTATUSES ( FRAUDSTATUSCODE );

ALTER TABLE FRAUDREQUEST
    ADD CONSTRAINT FRDRQST_RQST_TYPS_FK FOREIGN KEY ( REQUESTTYPECODE )
        REFERENCES FRAUDREQUESTTYPES ( REQUESTTYPECODE );		

ALTER TABLE FRAUDREQUESTHISTORY 
    ADD CONSTRAINT FRDRQSTHSTRY_FRDRQST_FK FOREIGN KEY ( FRAUDREQUESTID ) 
        REFERENCES FRAUDREQUEST ( FRAUDREQUESTID );
		
ALTER TABLE FRAUDREQUESTHISTORY
    ADD CONSTRAINT FRDRQSTHSTRY_FRDSTATUSES_FK FOREIGN KEY ( FRAUDSTATUSCODE )
        REFERENCES FRAUDSTATUSES ( FRAUDSTATUSCODE );

ALTER TABLE FRAUDREQUESTHISTORY
    ADD CONSTRAINT FRDRQSTHSTRY_RQSTTYPS_FK FOREIGN KEY ( REQUESTTYPECODE )
        REFERENCES FRAUDREQUESTTYPES ( REQUESTTYPECODE );

ALTER TABLE FRAUDREQUESTHISTORYDETAILS
    ADD CONSTRAINT FRDRQSTHSTRYDTL_FRDRQSTHTRY_FK FOREIGN KEY ( FRAUDREQUESTHISTORYID )
        REFERENCES FRAUDREQUESTHISTORY ( FRAUDREQUESTHISTORYID );

CREATE SEQUENCE FRAUDREQUEST_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE FRAUDREQUESTHISTORY_SEQ START WITH 1 NOCACHE ORDER;
CREATE SEQUENCE FRAUDREQUESTHISTORYDETAILS_SEQ START WITH 1 NOCACHE ORDER;